var files_dup =
[
    [ "Angle.cpp", "Angle_8cpp.html", null ],
    [ "Apparent.cpp", "Apparent_8cpp.html", null ],
    [ "CatalogEntry.cpp", "CatalogEntry_8cpp.html", null ],
    [ "Distance.cpp", "Distance_8cpp.html", null ],
    [ "Ecliptic.cpp", "Ecliptic_8cpp.html", null ],
    [ "EOP.cpp", "EOP_8cpp.html", null ],
    [ "Equatorial.cpp", "Equatorial_8cpp.html", null ],
    [ "Frame.cpp", "Frame_8cpp.html", null ],
    [ "Galactic.cpp", "Galactic_8cpp.html", null ],
    [ "Geometric.cpp", "Geometric_8cpp.html", null ],
    [ "Horizontal.cpp", "Horizontal_8cpp.html", null ],
    [ "Interval.cpp", "Interval_8cpp.html", null ],
    [ "Observer.cpp", "Observer_8cpp.html", null ],
    [ "Position.cpp", "Position_8cpp.html", "Position_8cpp" ],
    [ "Pressure.cpp", "Pressure_8cpp.html", null ],
    [ "Site.cpp", "Site_8cpp.html", null ],
    [ "Source.cpp", "Source_8cpp.html", null ],
    [ "Speed.cpp", "Speed_8cpp.html", null ],
    [ "Spherical.cpp", "Spherical_8cpp.html", null ],
    [ "supernovas.hpp", "supernovas_8hpp.html", "supernovas_8hpp" ],
    [ "System.cpp", "System_8cpp.html", null ],
    [ "Temperature.cpp", "Temperature_8cpp.html", null ],
    [ "Time.cpp", "Time_8cpp.html", null ],
    [ "TimeAngle.cpp", "TimeAngle_8cpp.html", null ],
    [ "Vector.cpp", "Vector_8cpp.html", "Vector_8cpp" ],
    [ "Velocity.cpp", "Velocity_8cpp.html", null ],
    [ "Weather.cpp", "Weather_8cpp.html", null ]
];