SuperNOVAS: /github/workspace/src/transform.c File Reference
transform.c File Reference
Functions
double app_to_cirs_ra (double jd_tt, enum novas_accuracy accuracy, double ra)
short cel2ter (double jd_ut1_high, double jd_ut1_low, double ut1_to_tt, enum novas_earth_rotation_measure erot, enum novas_accuracy accuracy, enum novas_equatorial_class coordType, double xp, double yp, const double *in, double *out)
double cirs_to_app_ra (double jd_tt, enum novas_accuracy accuracy, double ra)
int cirs_to_gcrs (double jd_tdb, enum novas_accuracy accuracy, const double *in, double *out)
int cirs_to_itrs (double jd_tt_high, double jd_tt_low, double ut1_to_tt, enum novas_accuracy accuracy, double xp, double yp, const double *in, double *out)
int cirs_to_tod (double jd_tt, enum novas_accuracy accuracy, const double *in, double *out)
int frame_tie (const double *in, enum novas_frametie_direction direction, double *out)
short gcrs2equ (double jd_tt, enum novas_dynamical_type sys, enum novas_accuracy accuracy, double rag, double decg, double *restrict ra, double *restrict dec)
int gcrs_to_cirs (double jd_tdb, enum novas_accuracy accuracy, const double *in, double *out)
int gcrs_to_j2000 (const double *in, double *out)
int gcrs_to_mod (double jd_tdb, const double *in, double *out)
int gcrs_to_tod (double jd_tdb, enum novas_accuracy accuracy, const double *in, double *out)
int itrs_to_cirs (double jd_tt_high, double jd_tt_low, double ut1_to_tt, enum novas_accuracy accuracy, double xp, double yp, const double *in, double *out)
int itrs_to_tod (double jd_tt_high, double jd_tt_low, double ut1_to_tt, enum novas_accuracy accuracy, double xp, double yp, const double *in, double *out)
int j2000_to_gcrs (const double *in, double *out)
int j2000_to_tod (double jd_tdb, enum novas_accuracy accuracy, const double *in, double *out)
int mod_to_gcrs (double jd_tdb, const double *in, double *out)
short ter2cel (double jd_ut1_high, double jd_ut1_low, double ut1_to_tt, enum novas_earth_rotation_measure erot, enum novas_accuracy accuracy, enum novas_equatorial_class coordType, double xp, double yp, const double *in, double *out)
int tod_to_cirs (double jd_tt, enum novas_accuracy accuracy, const double *in, double *out)
int tod_to_gcrs (double jd_tdb, enum novas_accuracy accuracy, const double *in, double *out)
int tod_to_itrs (double jd_tt_high, double jd_tt_low, double ut1_to_tt, enum novas_accuracy accuracy, double xp, double yp, const double *in, double *out)
int tod_to_j2000 (double jd_tdb, enum novas_accuracy accuracy, const double *in, double *out)
Detailed Description
Date
Created on Mar 6, 2025
Author
G. Kaplan and Attila Kovacs
Various functions to transform rectangular equatorial vectors (positions or velocities) between different equatorial coordinate systems.
Function Documentation
app_to_cirs_ra()
double app_to_cirs_ra (double jd_tt, enum novas_accuracy accuracy, double ra)
Converts an apparent right ascension coordinate (measured from the true equinox of date) to a CIRS R.A., measured from the CIO.
Parameters
jd_tt [day] Terrestrial Time (TT) based Julian date
accuracy NOVAS_FULL_ACCURACY (0) or NOVAS_REDUCED_ACCURACY (1)
ra [h] the apparent R.A. coordinate measured from the true equinox of date.
Returns
[h] The CIRS right ascension coordinate, measured from the CIO [0:24], or NAN if the accuracy is invalid, or if there wan an error from cio_ra().
Since
1.0.1
Author
Attila Kovacs
See also
cirs_to_app_ra(), tod_to_cirs()
References cio_ra().
cel2ter()
short cel2ter (double jd_ut1_high, double jd_ut1_low, double ut1_to_tt, enum novas_earth_rotation_measure erot, enum novas_accuracy accuracy, enum novas_equatorial_class coordType, double xp, double yp, const double * in, double * out)
Deprecated
This function can be confusing to use due to the input coordinate system being specified by a combination of two options. Use itrs_to_cirs() or itrs_to_tod() instead. You can then follow these with other conversions to GCRS (or whatever else) as appropriate.
Rotates a vector from the celestial to the terrestrial system. Specifically, it transforms a vector in the GCRS, or the dynamcal CIRS or TOD frames to the ITRS (a rotating earth-fixed system) by applying rotations for the GCRS-to-dynamical frame tie, precession, nutation, Earth rotation, and polar motion.
If 'system' is NOVAS_CIRS then method EROT_ERA must be used. Similarly, if 'system' is NOVAS_TOD then method must be EROT_ERA. Otherwise an error 3 is returned.
If both 'xp' and 'yp' are set to 0 no polar motion is included in the transformation.
REFERENCES:
Kaplan, G. H. et. al. (1989). Astron. Journ. 97, 1197-1210.
Kaplan, G. H. (2003), 'Another Look at Non-Rotating Origins', Proceedings of IAU XXV J oint Discussion 16.
Parameters
jd_ut1_high [day] High-order part of UT1 Julian date.
jd_ut1_low [day] Low-order part of UT1 Julian date.
ut1_to_tt [s] TT - UT1 Time difference in seconds
erot Unused.
accuracy NOVAS_FULL_ACCURACY (0) or NOVAS_REDUCED_ACCURACY (1)
coordType Input coordinate class, NOVAS_REFERENCE_CLASS (0) or NOVAS_DYNAMICAL_CLASS (1). Use the former if the input coordinates are in the GCRS, and the latter if they are CIRS or TOD (the 'erot' parameter selects which dynamical system the input is specified in.)
xp [arcsec] Conventionally-defined X coordinate of celestial intermediate pole with respect to ITRS pole, in arcseconds.
yp [arcsec] Conventionally-defined Y coordinate of celestial intermediate pole with respect to ITRS pole, in arcseconds.
in Input position vector, geocentric equatorial rectangular coordinates in the specified input coordinate system (GCRS if 'class' is NOVAS_REFERENCE_CLASS; or else either CIRS if 'erot' is EROT_ERA, or TOD if 'erot' is EROT_GST).
[out] out ITRS position vector, geocentric equatorial rectangular coordinates (terrestrial system). It can be the same vector as the input.
Returns
0 if successful, -1 if either of the vector arguments is NULL, 1 if 'accuracy' is invalid, 2 if 'method' is invalid, or else 10 + the error from cio_location(), or 20 + error from cio_basis().
See also
novas_app_to_hor(), gcrs_to_cirs(), cirs_to_itrs(), frame_tie(), j2000_to_tod(), tod_to_itrs(), ter2cel()
References era(), EROT_ERA, EROT_GST, gcrs_to_cirs(), gcrs_to_tod(), NOVAS_DYNAMICAL_CLASS, NOVAS_FULL_ACCURACY, novas_gast(), NOVAS_REDUCED_ACCURACY, spin(), wobble(), WOBBLE_PEF_TO_ITRS, and WOBBLE_TIRS_TO_ITRS.
cirs_to_app_ra()
double cirs_to_app_ra (double jd_tt, enum novas_accuracy accuracy, double ra)
Converts a CIRS right ascension coordinate (measured from the CIO) to an apparent R.A. measured from the true equinox of date.
Parameters
jd_tt [day] Terrestrial Time (TT) based Julian date
accuracy NOVAS_FULL_ACCURACY (0) or NOVAS_REDUCED_ACCURACY (1)
ra [h] The CIRS right ascension coordinate, measured from the CIO.
Returns
[h] the apparent R.A. coordinate measured from the true equinox of date [0:24], or NAN if the accuracy is invalid, or if there wan an error from cio_ra().
Since
1.0.1
Author
Attila Kovacs
See also
app_to_cirs_ra(), cirs_to_tod()
References cio_ra().
cirs_to_gcrs()
int cirs_to_gcrs (double jd_tdb, enum novas_accuracy accuracy, const double * in, double * out)
Transforms a rectangular equatorial (x, y, z) vector from the Celestial Intermediate Reference System (CIRS) frame at the given epoch to the Geocentric Celestial Reference System (GCRS).
Parameters
jd_tdb [day] Barycentric Dynamical Time (TDB) based Julian date that defines the output epoch. Typically it does not require much precision, and Julian dates in other time measures will be unlikely to affect the result
accuracy NOVAS_FULL_ACCURACY (0) or NOVAS_REDUCED_ACCURACY (1)
in CIRS Input (x, y, z) position or velocity vector
[out] out Output position or velocity 3-vector in the GCRS coordinate frame. It can be the same vector as the input.
Returns
0 if successful, or -1 if either of the vector arguments is NULL or the accuracy is invalid, or else 10 + the error from cio_basis().
Since
1.0
Author
Attila Kovacs
See also
tod_to_gcrs(), gcrs_to_cirs(), cirs_to_itrs(), cirs_to_tod()
References cirs_to_tod(), and tod_to_gcrs().
cirs_to_itrs()
int cirs_to_itrs (double jd_tt_high, double jd_tt_low, double ut1_to_tt, enum novas_accuracy accuracy, double xp, double yp, const double * in, double * out)
Rotates a position vector from the dynamical CIRS frame of date to the Earth-fixed ITRS frame (IAU 2000 standard method).
If both 'xp' and 'yp' are set to 0 no polar motion is included in the transformation.
If extreme (sub-microarcsecond) accuracy is not required, you can use UT1-based Julian date instead of the TT-based Julian date and set the 'ut1_to_tt' argument to 0.0. and you can use UTC-based Julian date the same way.for arcsec-level precision also.
REFERENCES:
Kaplan, G. H. et. al. (1989). Astron. Journ. 97, 1197-1210.
Kaplan, G. H. (2003), 'Another Look at Non-Rotating Origins', Proceedings of IAU XXV Joint Discussion 16.
Parameters
jd_tt_high [day] High-order part of Terrestrial Time (TT) based Julian date.
jd_tt_low [day] Low-order part of Terrestrial Time (TT) based Julian date.
ut1_to_tt [s] TT - UT1 Time difference in seconds
accuracy NOVAS_FULL_ACCURACY (0) or NOVAS_REDUCED_ACCURACY (1)
xp [arcsec] Conventionally-defined X coordinate of celestial intermediate pole with respect to ITRS pole, in arcseconds.
yp [arcsec] Conventionally-defined Y coordinate of celestial intermediate pole with respect to ITRS pole, in arcseconds.
in Position vector, geocentric equatorial rectangular coordinates, referred to CIRS axes (celestial system).
[out] out Position vector, geocentric equatorial rectangular coordinates, referred to ITRS axes (terrestrial system).
Returns
0 if successful, -1 if either of the vector arguments is NULL, 1 if 'accuracy' is invalid, 2 if 'method' is invalid 10–20, 3 if the method and option are mutually incompatible, or else 10 + the error from cio_location(), or 20 + error from cio_basis().
Since
1.0
Author
Attila Kovacs
See also
tod_to_itrs(), itrs_to_cirs(), gcrs_to_cirs(), cirs_to_gcrs(), cirs_to_tod()
References cel2ter(), EROT_ERA, and NOVAS_DYNAMICAL_CLASS.
cirs_to_tod()
int cirs_to_tod (double jd_tt, enum novas_accuracy accuracy, const double * in, double * out)
Transforms a rectangular equatorial (x, y, z) vector from the Celestial Intermediate Reference System (CIRS) at the given epoch to the True of Date (TOD) reference system.
Parameters
jd_tt [day] Terrestrial Time (TT) based Julian date that defines the output epoch. Typically it does not require much precision, and Julian dates in other time measures will be unlikely to affect the result
accuracy NOVAS_FULL_ACCURACY (0) or NOVAS_REDUCED_ACCURACY (1)
in CIRS Input (x, y, z) position or velocity vector
[out] out Output position or velocity 3-vector in the True of Date (TOD) frame. It can be the same vector as the input.
Returns
0 if successful, or -1 if either of the vector arguments is NULL or the accuracy is invalid, or else 20 + the error from cio_basis().
Since
1.1
Author
Attila Kovacs
See also
tod_to_cirs(), cirs_to_app_ra(), cirs_to_gcrs(), cirs_to_itrs()
References ira_equinox(), NOVAS_FULL_ACCURACY, NOVAS_REDUCED_ACCURACY, NOVAS_TRUE_EQUINOX, and spin().
frame_tie()
int frame_tie (const double * in, enum novas_frametie_direction direction, double * out)
Transforms a vector from the dynamical reference system to the International Celestial Reference System (ICRS), or vice versa. The dynamical reference system is based on the dynamical mean equator and equinox of J2000.0. The ICRS is based on the space-fixed ICRS axes defined by the radio catalog positions of several hundred extragalactic objects.
For geocentric coordinates, the same transformation is used between the dynamical reference system and the GCRS.
NOTES:
More efficient 3D rotation implementation for small angles by A. Kovacs
REFERENCES:
Hilton, J. and Hohenkerk, C. (2004), Astronomy and Astrophysics 413, 765-770, eq. (6) and (8).
IERS (2003) Conventions, Chapter 5.
Parameters
in Position vector, equatorial rectangular coordinates.
direction <0 for for dynamical to ICRS transformation, or else >=0 for ICRS to dynamical transformation. Alternatively you may use the constants J2000_TO_ICRS (-1; or negative) or ICRS_TO_J2000 (0; or positive).
[out] out Position vector, equatorial rectangular coordinates. It can be the same vector as the input.
Returns
0 if successfor or -1 if either of the vector arguments is NULL.
See also
j2000_to_gcrs(), gcrs_to_j2000(), tod_to_j2000(), j2000_to_tod(), j2000_to_gcrs()
gcrs2equ()
short gcrs2equ (double jd_tt, enum novas_dynamical_type sys, enum novas_accuracy accuracy, double rag, double decg, double *restrict ra, double *restrict dec)
Converts GCRS right ascension and declination to coordinates with respect to the equator of date (mean or true). For coordinates with respect to the true equator of date, the origin of right ascension can be either the true equinox or the celestial intermediate origin (CIO). This function only supports the CIO-based method.
Parameters
jd_tt [day] Terrestrial Time (TT) based Julian date. (Unused if 'coord_sys' is NOVAS_ICRS_EQUATOR)
sys Dynamical equatorial system type
accuracy NOVAS_FULL_ACCURACY (0) or NOVAS_REDUCED_ACCURACY (1) (unused if 'coord_sys' is not NOVAS_ICRS [3])
rag [h] GCRS right ascension in hours.
decg [deg] GCRS declination in degrees.
[out] ra [h] Right ascension in hours, referred to specified equator and right ascension origin of date.
[out] dec [deg] Declination in degrees, referred to specified equator of date.
Returns
0 if successful, or -1 with errno set to EINVAL if the output pointers are NULL or the coord_sys is invalid, otherwise <0 if an error from vector2radec(), 10–20 error is 10 + error cio_location(); or else 20 + error from cio_basis()
References DEG2RAD, gcrs_to_cirs(), gcrs_to_mod(), gcrs_to_tod(), NOVAS_DYNAMICAL_CIRS, NOVAS_DYNAMICAL_MOD, NOVAS_DYNAMICAL_TOD, and vector2radec().
gcrs_to_cirs()
int gcrs_to_cirs (double jd_tdb, enum novas_accuracy accuracy, const double * in, double * out)
Transforms a rectangular equatorial (x, y, z) vector from the Geocentric Celestial Reference System (GCRS) to the Celestial Intermediate Reference System (CIRS) frame at the given epoch
Parameters
jd_tdb [day] Barycentric Dynamical Time (TDB) based Julian date that defines the output epoch. Typically it does not require much precision, and Julian dates in other time measures will be unlikely to affect the result
accuracy NOVAS_FULL_ACCURACY (0) or NOVAS_REDUCED_ACCURACY (1)
in GCRS Input (x, y, z) position or velocity vector
[out] out Output position or velocity 3-vector in the True equinox of Date coordinate frame. It can be the same vector as the input.
Returns
0 if successful, or -1 if either of the vector arguments is NULL or the accuracy is invalid, or else 10 + the error from cio_basis().
Since
1.0
Author
Attila Kovacs
See also
gcrs_to_j2000(), cirs_to_gcrs()
References gcrs_to_tod(), and tod_to_cirs().
gcrs_to_j2000()
int gcrs_to_j2000 (const double * in, double * out)
Change GCRS coordinates to J2000 coordinates. Same as frame_tie() called with ICRS_TO_J2000
Parameters
in GCRS input 3-vector
[out] out J2000 output 3-vector
Returns
0 if successful, or else an error from frame_tie()
Since
1.0
Author
Attila Kovacs
See also
j2000_to_gcrs(), tod_to_j2000()
References frame_tie(), and ICRS_TO_J2000.
gcrs_to_mod()
int gcrs_to_mod (double jd_tdb, const double * in, double * out)
Transforms a rectangular equatorial (x, y, z) vector from the Geocentric Celestial Reference System (GCRS) to the Mean of Date (MOD) reference frame at the given epoch
Parameters
jd_tdb [day] Barycentric Dynamical Time (TT) based Julian date that defines the output epoch. Typically it does not require much precision, and Julian dates in other time measures will be unlikely to affect the result
in GCRS Input (x, y, z) position or velocity vector
[out] out Output position or velocity 3-vector in the Mean wquinox of Date coordinate frame. It can be the same vector as the input.
Returns
0 if successful, or -1 if either of the vector arguments is NULL.
Since
1.2
Author
Attila Kovacs
See also
mod_to_gcrs(), gcrs_to_tod()
References frame_tie(), ICRS_TO_J2000, NOVAS_JD_J2000, and precession().
gcrs_to_tod()
int gcrs_to_tod (double jd_tdb, enum novas_accuracy accuracy, const double * in, double * out)
Transforms a rectangular equatorial (x, y, z) vector from the Geocentric Celestial Reference System (GCRS) to the True of Date (TOD) reference frame at the given epoch
Parameters
jd_tdb [day] Barycentric Dynamical Time (TT) based Julian date that defines the output epoch. Typically it does not require much precision, and Julian dates in other time measures will be unlikely to affect the result
accuracy NOVAS_FULL_ACCURACY (0) or NOVAS_REDUCED_ACCURACY (1)
in GCRS Input (x, y, z) position or velocity vector
[out] out Output position or velocity 3-vector in the True equinox of Date coordinate frame. It can be the same vector as the input.
Returns
0 if successful, or -1 if either of the vector arguments is NULL.
Since
1.2
Author
Attila Kovacs
See also
gcrs_to_cirs(), tod_to_gcrs(), j2000_to_tod()
References frame_tie(), ICRS_TO_J2000, and j2000_to_tod().
itrs_to_cirs()
int itrs_to_cirs (double jd_tt_high, double jd_tt_low, double ut1_to_tt, enum novas_accuracy accuracy, double xp, double yp, const double * in, double * out)
Rotates a position vector from the Earth-fixed ITRS frame to the dynamical CIRS frame of date (IAU 2000 standard method).
If both 'xp' and 'yp' are set to 0 no polar motion is included in the transformation.
If extreme (sub-microarcsecond) accuracy is not required, you can use UT1-based Julian date instead of the TT-based Julian date and set the 'ut1_to_tt' argument to 0.0. and you can use UTC-based Julian date the same way.for arcsec-level precision also.
REFERENCES:
Kaplan, G. H. et. al. (1989). Astron. Journ. 97, 1197-1210.
Kaplan, G. H. (2003), 'Another Look at Non-Rotating Origins', Proceedings of IAU XXV Joint Discussion 16.
Parameters
jd_tt_high [day] High-order part of Terrestrial Time (TT) based Julian date.
jd_tt_low [day] Low-order part of Terrestrial Time (TT) based Julian date.
ut1_to_tt [s] TT - UT1 Time difference in seconds
accuracy NOVAS_FULL_ACCURACY (0) or NOVAS_REDUCED_ACCURACY (1)
xp [arcsec] Conventionally-defined X coordinate of celestial intermediate pole with respect to ITRS pole, in arcseconds.
yp [arcsec] Conventionally-defined Y coordinate of celestial intermediate pole with respect to ITRS pole, in arcseconds.
in Position vector, geocentric equatorial rectangular coordinates, referred to ITRS axes (terrestrial system)
[out] out Position vector, geocentric equatorial rectangular coordinates, referred to CIRS axes (celestial system).
Returns
0 if successful, -1 if either of the vector arguments is NULL, 1 if 'accuracy' is invalid, or else 10 + the error from cio_location(), or 20 + error from cio_basis().
Since
1.0
Author
Attila Kovacs
See also
itrs_to_tod(), cirs_to_itrs(), cirs_to_gcrs()
References EROT_ERA, NOVAS_DYNAMICAL_CLASS, and ter2cel().
itrs_to_tod()
int itrs_to_tod (double jd_tt_high, double jd_tt_low, double ut1_to_tt, enum novas_accuracy accuracy, double xp, double yp, const double * in, double * out)
Rotates a position vector from the Earth-fixed ITRS frame to the dynamical True of Date (TOD) frame of date (pre IAU 2000 method).
If both 'xp' and 'yp' are set to 0 no polar motion is included in the transformation.
If extreme (sub-microarcsecond) accuracy is not required, you can use UT1-based Julian date instead of the TT-based Julian date and set the 'ut1_to_tt' argument to 0.0. and you can use UTC-based Julian date the same way.for arcsec-level precision also.
REFERENCES:
Kaplan, G. H. et. al. (1989). Astron. Journ. 97, 1197-1210.
Kaplan, G. H. (2003), 'Another Look at Non-Rotating Origins', Proceedings of IAU XXV Joint Discussion 16.
Parameters
jd_tt_high [day] High-order part of Terrestrial Time (TT) based Julian date.
jd_tt_low [day] Low-order part of Terrestrial Time (TT) based Julian date.
ut1_to_tt [s] TT - UT1 Time difference in seconds
accuracy NOVAS_FULL_ACCURACY (0) or NOVAS_REDUCED_ACCURACY (1)
xp [arcsec] Conventionally-defined X coordinate of celestial intermediate pole with respect to ITRS pole, in arcseconds.
yp [arcsec] Conventionally-defined Y coordinate of celestial intermediate pole with respect to ITRS pole, in arcseconds.
in Position vector, geocentric equatorial rectangular coordinates, referred to ITRS axes (terrestrial system)
[out] out Position vector, geocentric equatorial rectangular coordinates, referred to True of Date (TOD) axes (celestial system)
Returns
0 if successful, -1 if either of the vector arguments is NULL, 1 if 'accuracy' is invalid, or else 10 + the error from cio_location(), or 20 + error from cio_basis().
Since
1.0
Author
Attila Kovacs
See also
itrs_to_cirs(), tod_to_itrs(), tod_to_j2000()
References EROT_GST, NOVAS_DYNAMICAL_CLASS, and ter2cel().
j2000_to_gcrs()
int j2000_to_gcrs (const double * in, double * out)
Change J2000 coordinates to GCRS coordinates. Same as frame_tie() called with J2000_TO_ICRS
Parameters
in J2000 input 3-vector
[out] out GCRS output 3-vector
Returns
0 if successful, or else an error from frame_tie()
Since
1.0
Author
Attila Kovacs
See also
j2000_to_tod(), gcrs_to_j2000()
References frame_tie(), and J2000_TO_ICRS.
j2000_to_tod()
int j2000_to_tod (double jd_tdb, enum novas_accuracy accuracy, const double * in, double * out)
Transforms a rectangular equatorial (x, y, z) vector from J2000 coordinates to the True of Date (TOD) reference frame at the given epoch
Parameters
jd_tdb [day] Barycentric Dynamical Time (TDB) based Julian date that defines the output epoch. Typically it does not require much precision, and Julian dates in other time measures will be unlikely to affect the result
accuracy NOVAS_FULL_ACCURACY (0) or NOVAS_REDUCED_ACCURACY (1)
in Input (x, y, z) position or velocity vector in rectangular equatorial coordinates at J2000
[out] out Output position or velocity 3-vector in the True equinox of Date coordinate frame. It can be the same vector as the input.
Returns
0 if successful, or -1 if either of the vector arguments is NULL or the accuracy is invalid.
Since
1.0
Author
Attila Kovacs
See also
j2000_to_gcrs(), tod_to_j2000(), gcrs_to_j2000()
References NOVAS_FULL_ACCURACY, NOVAS_REDUCED_ACCURACY, NUTATE_MEAN_TO_TRUE, nutation(), and precession().
mod_to_gcrs()
int mod_to_gcrs (double jd_tdb, const double * in, double * out)
Transforms a rectangular equatorial (x, y, z) vector from Mean of Date (MOD) reference frame at the given epoch to the Geocentric Celestial Reference System(GCRS)
Parameters
jd_tdb [day] Barycentric Dynamical Time (TDB) based Julian date that defines the input epoch. Typically it does not require much precision, and Julian dates in other time measures will be unlikely to affect the result
in Input (x, y, z) position or velocity 3-vector in the Mean equinox of Date coordinate frame.
[out] out Output GCRS position or velocity vector. It can be the same vector as the input.
Returns
0 if successful, or -1 if either of the vector arguments is NULL.
Since
1.2
Author
Attila Kovacs
See also
gcrs_to_mod(), tod_to_gcrs()
References frame_tie(), J2000_TO_ICRS, NOVAS_JD_J2000, and precession().
ter2cel()
short ter2cel (double jd_ut1_high, double jd_ut1_low, double ut1_to_tt, enum novas_earth_rotation_measure erot, enum novas_accuracy accuracy, enum novas_equatorial_class coordType, double xp, double yp, const double * in, double * out)
Deprecated
This function can be confusing to use due to the output coordinate system being specified by a combination of two options. Use itrs_to_cirs() or itrs_to_tod() instead. You can then follow these with other conversions to GCRS (or whatever else) as appropriate.
Rotates a vector from the terrestrial to the celestial system. Specifically, it transforms a vector in the ITRS (rotating earth-fixed system) to the True of Date (TOD), CIRS, or GCRS (a local space-fixed system) by applying rotations for polar motion, Earth rotation (for TOD); and nutation, precession, and the dynamical-to-GCRS frame tie (for GCRS).
If 'system' is NOVAS_CIRS then method EROT_ERA must be used. Similarly, if 'system' is NOVAS_TOD then method must be EROT_ERA. Otherwise an error 3 is returned.
If both 'xp' and 'yp' are set to 0 no polar motion is included in the transformation.
REFERENCES:
Kaplan, G. H. et. al. (1989). Astron. Journ. 97, 1197-1210.
Kaplan, G. H. (2003), 'Another Look at Non-Rotating Origins', Proceedings of IAU XXV Joint Discussion 16.
Parameters
jd_ut1_high [day] High-order part of UT1 Julian date.
jd_ut1_low [day] Low-order part of UT1 Julian date.
ut1_to_tt [s] TT - UT1 Time difference in seconds
erot Unused.
accuracy NOVAS_FULL_ACCURACY (0) or NOVAS_REDUCED_ACCURACY (1)
coordType Output coordinate class NOVAS_REFERENCE_CLASS (0, or any value other than 1) or NOVAS_DYNAMICAL_CLASS (1). Use the former if the output coordinates are to be in the GCRS, and the latter if they are to be in CIRS or TOD (the 'erot' parameter selects which dynamical system to use for the output.)
xp [arcsec] Conventionally-defined X coordinate of celestial intermediate pole with respect to ITRS pole, in arcseconds.
yp [arcsec] Conventionally-defined Y coordinate of celestial intermediate pole with respect to ITRS pole, in arcseconds.
in Position vector, geocentric equatorial rectangular coordinates, referred to ITRS axes (terrestrial system) in the normal case where 'option' is NOVAS_GCRS (0).
[out] out Position vector, equatorial rectangular coordinates in the specified output system (GCRS if 'class' is NOVAS_REFERENCE_CLASS; or else either CIRS if 'erot' is EROT_ERA, or TOD if 'erot' is EROT_GST). It may be the same vector as the input.
Returns
0 if successful, -1 if either of the vector arguments is NULL, 1 if 'accuracy' is invalid, 2 if 'method' is invalid 10–20, or else 10 + the error from cio_location(), or 20 + error from cio_basis().
See also
novas_hor_to_app(), itrs_to_cirs(), cirs_to_gcrs(), itrs_to_tod(), tod_to_j2000(), frame_tie(), cel2ter()
References cirs_to_gcrs(), era(), EROT_ERA, EROT_GST, NOVAS_DYNAMICAL_CLASS, NOVAS_FULL_ACCURACY, novas_gast(), NOVAS_REDUCED_ACCURACY, spin(), tod_to_gcrs(), wobble(), WOBBLE_ITRS_TO_PEF, and WOBBLE_ITRS_TO_TIRS.
tod_to_cirs()
int tod_to_cirs (double jd_tt, enum novas_accuracy accuracy, const double * in, double * out)
Transforms a rectangular equatorial (x, y, z) vector from the True of Date (TOD) reference system to the Celestial Intermediate Reference System (CIRS) at the given epoch to the .
NOTES:
The accuracy of the output CIRS coordinates depends on how the input TOD coordinates were obtained. If TOD was calculated via the old (pre IAU 2006) method, using the Lieske et al. 1997 nutation model, then the limited accuracy of that model will affect the resulting coordinates. This is the case for the SuperNOVAS functions novas_geom_posvel() and novas_sky_pos() also, when called with NOVAS_TOD as the system, as well as all legacy NOVAS C functions that produce TOD coordinates.
Parameters
jd_tt [day] Terrestrial Time (TT) based Julian date that defines the output epoch. Typically it does not require much precision, and Julian dates in other time measures will be unlikely to affect the result
accuracy NOVAS_FULL_ACCURACY (0) or NOVAS_REDUCED_ACCURACY (1)
in CIRS Input (x, y, z) position or velocity vector
[out] out Output position or velocity 3-vector in the True of Date (TOD) frame. It can be the same vector as the input.
Returns
0 if successful, or -1 if either of the vector arguments is NULL or the accuracy is invalid, or 10 + the error from cio_ra(), or else 20 + the error from cio_basis().
Since
1.1
Author
Attila Kovacs
See also
cirs_to_tod(), app_to_cirs_ra(), tod_to_gcrs(), tod_to_j2000(), tod_to_itrs()
References cio_ra(), and spin().
tod_to_gcrs()
int tod_to_gcrs (double jd_tdb, enum novas_accuracy accuracy, const double * in, double * out)
Transforms a rectangular equatorial (x, y, z) vector from True of Date (TOD) reference frame at the given epoch to the Geocentric Celestial Reference System(GCRS)
Parameters
jd_tdb [day] Barycentric Dynamical Time (TDB) based Julian date that defines the input epoch. Typically it does not require much precision, and Julian dates in other time measures will be unlikely to affect the result
accuracy NOVAS_FULL_ACCURACY (0) or NOVAS_REDUCED_ACCURACY (1)
in Input (x, y, z) position or velocity 3-vector in the True equinox of Date coordinate frame.
[out] out Output GCRS position or velocity vector. It can be the same vector as the input.
Returns
0 if successful, or -1 if either of the vector arguments is NULL.
Since
1.2
Author
Attila Kovacs
See also
j2000_to_tod(), tod_to_cirs(), tod_to_j2000(), tod_to_itrs()
References frame_tie(), J2000_TO_ICRS, and tod_to_j2000().
tod_to_itrs()
int tod_to_itrs (double jd_tt_high, double jd_tt_low, double ut1_to_tt, enum novas_accuracy accuracy, double xp, double yp, const double * in, double * out)
Rotates a position vector from the dynamical True of Date (TOD) frame of date the Earth-fixed ITRS frame (pre IAU 2000 method).
If both 'xp' and 'yp' are set to 0 no polar motion is included in the transformation.
If extreme (sub-microarcsecond) accuracy is not required, you can use UT1-based Julian date instead of the TT-based Julian date and set the 'ut1_to_tt' argument to 0.0. and you can use UTC-based Julian date the same way.for arcsec-level precision also.
REFERENCES:
Kaplan, G. H. et. al. (1989). Astron. Journ. 97, 1197-1210.
Kaplan, G. H. (2003), 'Another Look at Non-Rotating Origins', Proceedings of IAU XXV Joint Discussion 16.
Parameters
jd_tt_high [day] High-order part of Terrestrial Time (TT) based Julian date.
jd_tt_low [day] Low-order part of Terrestrial Time (TT) based Julian date.
ut1_to_tt [s] TT - UT1 Time difference in seconds.
accuracy NOVAS_FULL_ACCURACY (0) or NOVAS_REDUCED_ACCURACY (1)
xp [arcsec] Conventionally-defined X coordinate of celestial intermediate pole with respect to ITRS pole, in arcseconds.
yp [arcsec] Conventionally-defined Y coordinate of celestial intermediate pole with respect to ITRS pole, in arcseconds.
in Position vector, geocentric equatorial rectangular coordinates, referred to True of Date (TOD) axes (celestial system).
[out] out Position vector, geocentric equatorial rectangular coordinates, referred to ITRS axes (terrestrial system).
Returns
0 if successful, -1 if either of the vector arguments is NULL, 1 if 'accuracy' is invalid, 2 if 'method' is invalid 10–20, 3 if the method and option are mutually incompatible, or else 10 + the error from cio_location(), or 20 + error from cio_basis().
Since
1.0
Author
Attila Kovacs
See also
cirs_to_itrs(), itrs_to_tod(), j2000_to_tod(), tod_to_gcrs(), tod_to_j2000(), tod_to_cirs()
References cel2ter(), EROT_GST, and NOVAS_DYNAMICAL_CLASS.
tod_to_j2000()
int tod_to_j2000 (double jd_tdb, enum novas_accuracy accuracy, const double * in, double * out)
Transforms a rectangular equatorial (x, y, z) vector from True of Date (TOD) reference frame at the given epoch to the J2000 coordinates.
Parameters
jd_tdb [day] Barycentric Dynamical Time (TDB) based Julian date that defines the input epoch. Typically it does not require much precision, and Julian dates in other time measures will be unlikely to affect the result
accuracy NOVAS_FULL_ACCURACY (0) or NOVAS_REDUCED_ACCURACY (1)
in Input (x, y, z) position or velocity 3-vector in the True equinox of Date coordinate frame.
[out] out Output position or velocity vector in rectangular equatorial coordinates at J2000. It can be the same vector as the input.
Returns
0 if successful, or -1 if either of the vector arguments is NULL or the 'accuracy' is invalid.
Since
1.0
Author
Attila Kovacs
See also
j2000_to_tod(), j2000_to_gcrs(), tod_to_gcrs(), tod_to_cirs(), tod_to_itrs()
References NOVAS_FULL_ACCURACY, NOVAS_REDUCED_ACCURACY, NUTATE_TRUE_TO_MEAN, nutation(), and precession().