var searchData=
[
  ['object_0',['object',['../structobject.html',1,'']]],
  ['object_20of_20interest_1',['object of interest',['../index.html#autotoc_md45',1,'Specify the object of interest'],['../md_LEGACY.html#autotoc_md22',1,'Specify the object of interest']]],
  ['obs_5fplanets_2',['obs_planets',['../novas_8c.html#acbc29fe86915ef8a3701795dc9fd9b34',1,'obs_planets(double jd_tdb, enum novas_accuracy accuracy, const double *pos_obs, int pl_mask, novas_planet_bundle *planets):&#160;novas.c'],['../novas_8h.html#acbc29fe86915ef8a3701795dc9fd9b34',1,'obs_planets(double jd_tdb, enum novas_accuracy accuracy, const double *pos_obs, int pl_mask, novas_planet_bundle *planets):&#160;novas.c']]],
  ['obs_5fpos_3',['obs_pos',['../structnovas__frame.html#ac2558d2b29171b29bad2599c75d3cc6c',1,'novas_frame']]],
  ['obs_5fposvel_4',['obs_posvel',['../novas_8c.html#a5a62b6e1ef8840a1203c6d2a75d17152',1,'obs_posvel(double jd_tdb, double ut1_to_tt, enum novas_accuracy accuracy, const observer *obs, const double *geo_pos, const double *geo_vel, double *pos, double *vel):&#160;novas.c'],['../novas_8h.html#a5a62b6e1ef8840a1203c6d2a75d17152',1,'obs_posvel(double jd_tdb, double ut1_to_tt, enum novas_accuracy accuracy, const observer *obs, const double *geo_pos, const double *geo_vel, double *pos, double *vel):&#160;novas.c']]],
  ['obs_5fvel_5',['obs_vel',['../structnovas__frame.html#a66f1e86da27c96c1c920dce442ce78c8',1,'novas_frame']]],
  ['observation_6',['observation',['../md_LEGACY.html#autotoc_md24',1,'Specify the time of observation'],['../index.html#autotoc_md47',1,'Specify the time of observation']]],
  ['observer_7',['observer',['../structobserver.html',1,'observer'],['../structnovas__frame.html#aa792216b0b2601bb9af3b882c87274f8',1,'novas_frame::observer']]],
  ['observer_20location_8',['observer location',['../index.html#autotoc_md46',1,'Specify the observer location'],['../md_LEGACY.html#autotoc_md23',1,'Spefify the observer location']]],
  ['observing_20frame_9',['Set up the observing frame',['../index.html#autotoc_md48',1,'']]],
  ['observing_20location_10',['observing location',['../md_LEGACY.html#autotoc_md28',1,'B. Azimuth and elevation angles at the observing location'],['../index.html#autotoc_md50',1,'Calculate azimuth and elevation angles at the observing location']]],
  ['of_20contents_11',['Table of Contents',['../index.html#autotoc_md30',1,'']]],
  ['of_20custom_20ephemeris_20functions_12',['Legacy linking of custom ephemeris functions',['../index.html#autotoc_md72',1,'']]],
  ['of_20interest_13',['of interest',['../index.html#autotoc_md45',1,'Specify the object of interest'],['../md_LEGACY.html#autotoc_md22',1,'Specify the object of interest']]],
  ['of_20observation_14',['of observation',['../md_LEGACY.html#autotoc_md24',1,'Specify the time of observation'],['../index.html#autotoc_md47',1,'Specify the time of observation']]],
  ['old_20way_15',['SuperNOVAS: Astrometric Positions the Old Way',['../md_LEGACY.html',1,'']]],
  ['older_20jpl_20major_20planet_20ephemerides_16',['Legacy support for (older) JPL major planet ephemerides',['../index.html#autotoc_md69',1,'']]],
  ['omega_17',['Omega',['../structnovas__delaunay__args.html#a1b5bf6735b7465aec5c931281d240737',1,'novas_delaunay_args']]],
  ['on_20alternative_20methodologies_18',['Note on alternative methodologies',['../index.html#autotoc_md43',1,'']]],
  ['on_20precision_19',['Notes on precision',['../index.html#autotoc_md56',1,'']]],
  ['on_20sky_20',['on sky',['../index.html#autotoc_md49',1,'Calculate an apparent place on sky'],['../md_LEGACY.html#autotoc_md26',1,'Calculate apparent positions on sky']]],
  ['on_5fsurf_21',['on_surf',['../structobserver.html#a0ed422bd2a08c6b3870b545e16484501',1,'observer']]],
  ['on_5fsurface_22',['on_surface',['../structon__surface.html',1,'']]],
  ['optional_20calceph_20integration_23',['Optional CALCEPH integration',['../index.html#autotoc_md66',1,'']]],
  ['optional_20naif_20cspice_20toolkit_20integration_24',['Optional NAIF CSPICE toolkit integration',['../index.html#autotoc_md67',1,'']]],
  ['or_20services_25',['Incorporating Solar-system ephemeris data or services',['../index.html#autotoc_md65',1,'']]],
  ['orientation_20parameters_26',['Specify Earth orientation parameters',['../md_LEGACY.html#autotoc_md25',1,'']]]
];
