var searchData=
[
  ['object_0',['object',['../structobject.html',1,'']]],
  ['object_20of_20interest_1',['object of interest',['../index.html#autotoc_md41',1,'Specify the object of interest'],['../md_LEGACY.html#autotoc_md16',1,'Specify the object of interest']]],
  ['obs_5fpos_2',['obs_pos',['../structnovas__frame.html#ac2558d2b29171b29bad2599c75d3cc6c',1,'novas_frame']]],
  ['obs_5fposvel_3',['obs_posvel',['../novas_8c.html#a5a62b6e1ef8840a1203c6d2a75d17152',1,'obs_posvel(double jd_tdb, double ut1_to_tt, enum novas_accuracy accuracy, const observer *obs, const double *geo_pos, const double *geo_vel, double *pos, double *vel):&#160;novas.c'],['../novas_8h.html#a5a62b6e1ef8840a1203c6d2a75d17152',1,'obs_posvel(double jd_tdb, double ut1_to_tt, enum novas_accuracy accuracy, const observer *obs, const double *geo_pos, const double *geo_vel, double *pos, double *vel):&#160;novas.c']]],
  ['obs_5fvel_4',['obs_vel',['../structnovas__frame.html#a66f1e86da27c96c1c920dce442ce78c8',1,'novas_frame']]],
  ['observation_5',['observation',['../md_LEGACY.html#autotoc_md18',1,'Specify the time of observation'],['../index.html#autotoc_md43',1,'Specify the time of observation']]],
  ['observer_6',['observer',['../structobserver.html',1,'observer'],['../structnovas__frame.html#aa792216b0b2601bb9af3b882c87274f8',1,'novas_frame::observer']]],
  ['observer_20location_7',['observer location',['../md_LEGACY.html#autotoc_md17',1,'Spefify the observer location'],['../index.html#autotoc_md42',1,'Spefify the observer location']]],
  ['observing_20frame_8',['Set up the observing frame',['../index.html#autotoc_md44',1,'']]],
  ['observing_20location_9',['observing location',['../md_LEGACY.html#autotoc_md22',1,'B. Azimuth and elevation angles at the observing location'],['../index.html#autotoc_md46',1,'Calculate azimuth and elevation angles at the observing location']]],
  ['of_20contents_10',['Table of Contents',['../index.html#autotoc_md27',1,'']]],
  ['of_20custom_20ephemeris_20functions_11',['3. Explicit linking of custom ephemeris functions',['../index.html#autotoc_md65',1,'']]],
  ['of_20interest_12',['of interest',['../index.html#autotoc_md41',1,'Specify the object of interest'],['../md_LEGACY.html#autotoc_md16',1,'Specify the object of interest']]],
  ['of_20observation_13',['of observation',['../md_LEGACY.html#autotoc_md18',1,'Specify the time of observation'],['../index.html#autotoc_md43',1,'Specify the time of observation']]],
  ['old_20jpl_20major_20planet_20ephemerides_14',['2. Built-in support for (old) JPL major planet ephemerides',['../index.html#autotoc_md62',1,'']]],
  ['omega_15',['Omega',['../structnovas__delaunay__args.html#a1b5bf6735b7465aec5c931281d240737',1,'novas_delaunay_args']]],
  ['on_20alternative_20methodologies_16',['Note on alternative methodologies',['../index.html#autotoc_md39',1,'']]],
  ['on_20precision_17',['Notes on precision',['../index.html#autotoc_md53',1,'']]],
  ['on_20sky_18',['on sky',['../index.html#autotoc_md45',1,'Calculate an apparent place on sky'],['../md_LEGACY.html#autotoc_md20',1,'Calculate apparent positions on sky']]],
  ['on_5fsurf_19',['on_surf',['../structobserver.html#a0ed422bd2a08c6b3870b545e16484501',1,'observer']]],
  ['on_5fsurface_20',['on_surface',['../structon__surface.html',1,'']]],
  ['or_20services_21',['External Solar-system ephemeris data or services',['../index.html#autotoc_md60',1,'']]],
  ['orientation_20parameters_22',['Specify Earth orientation parameters',['../md_LEGACY.html#autotoc_md19',1,'']]]
];
