.TH "cat_entry" 3 "Version v1.2" "SuperNOVAS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cat_entry
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <novas\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBcatalog\fP [\fBSIZE_OF_CAT_NAME\fP]"
.br
.RI "catalog designator (e\&.g\&., HIP) "
.ti -1c
.RI "double \fBdec\fP"
.br
.RI "[deg] ICRS declination "
.ti -1c
.RI "double \fBparallax\fP"
.br
.RI "[mas] parallax "
.ti -1c
.RI "double \fBpromodec\fP"
.br
.RI "[mas/yr] ICRS proper motion in declination "
.ti -1c
.RI "double \fBpromora\fP"
.br
.RI "[mas/yr] ICRS proper motion in right ascension "
.ti -1c
.RI "double \fBra\fP"
.br
.RI "[h] ICRS right ascension "
.ti -1c
.RI "double \fBradialvelocity\fP"
.br
.ti -1c
.RI "char \fBstarname\fP [\fBSIZE_OF_OBJ_NAME\fP]"
.br
.RI "name of celestial object "
.ti -1c
.RI "long \fBstarnumber\fP"
.br
.RI "integer identifier assigned to object "
.in -1c
.SH "Detailed Description"
.PP 
Basic astrometric data for any sidereal object located outside the solar system\&.
.PP
Note, that despite the slightly expanded catalog name, this has the same memory footprint as the original NOVAS C version, allowing for cross-compatible binary exchange (I/O) of these structures\&.
.PP
\fBSee also\fP
.RS 4
\fBCAT_ENTRY_INIT\fP 
.RE
.PP

.SH "Field Documentation"
.PP 
.SS "double radialvelocity"
[km/s] catalog radial velocity (w\&.r\&.t\&. SSB) To specify radial velocities defined in the Local Standard of Rest (LSR) you might use novas_set_lsr_vel() 

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperNOVAS from the source code\&.
