.TH "src/eph_manager.c" 3 "Version v1.1" "SuperNOVAS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/eph_manager.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "short \fBephem_close\fP (void)"
.br
.ti -1c
.RI "short \fBephem_open\fP (const char *ephem_name, double *jd_begin, double *jd_end, short *de_number)"
.br
.ti -1c
.RI "int \fBinterpolate\fP (const double *buf, const double *t, long ncf, long na, double *position, double *velocity)"
.br
.ti -1c
.RI "short \fBplanet_ephemeris\fP (const double tjd[2], enum de_planet target, enum de_planet origin, double *position, double *velocity)"
.br
.ti -1c
.RI "int \fBsplit\fP (double tt, double *fr)"
.br
.ti -1c
.RI "short \fBstate\fP (const double *jed, enum de_planet target, double *target_pos, double *target_vel)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "double * \fBBUFFER\fP"
.br
.RI "(\fIfor internal use\fP) Array containing Chebyshev coefficients of position\&. "
.ti -1c
.RI "double \fBEM_RATIO\fP"
.br
.RI "(\fIfor internal use\fP) "
.ti -1c
.RI "FILE * \fBEPHFILE\fP = NULL"
.br
.RI "(\fIfor internal use\fP) The currently open JPL DE planetary ephemeris file "
.ti -1c
.RI "int \fBIPT\fP [3][12]"
.br
.RI "(\fIfor internal use\fP) "
.ti -1c
.RI "double \fBJPLAU\fP"
.br
.RI "(\fIfor internal use\fP) "
.ti -1c
.RI "short \fBKM\fP"
.br
.RI "Flag that defines physical units of the output states\&. "
.ti -1c
.RI "int \fBLPT\fP [3]"
.br
.RI "(\fIfor internal use\fP) "
.ti -1c
.RI "long \fBNP\fP"
.br
.RI "(\fIfor internal use\fP) "
.ti -1c
.RI "long \fBNRL\fP"
.br
.RI "(\fIfor internal use\fP) Current record number buffered "
.ti -1c
.RI "long \fBNV\fP"
.br
.RI "(\fIfor internal use\fP) "
.ti -1c
.RI "double \fBPC\fP [18]"
.br
.RI "(\fIfor internal use\fP) "
.ti -1c
.RI "long \fBRECORD_LENGTH\fP"
.br
.RI "(\fIfor internal use\fP) "
.ti -1c
.RI "double \fBSS\fP [3]"
.br
.RI "(\fIfor internal use\fP) "
.ti -1c
.RI "double \fBTWOT\fP"
.br
.RI "(\fIfor internal use\fP) "
.ti -1c
.RI "double \fBVC\fP [18]"
.br
.RI "(\fIfor internal use\fP) "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
G\&. Kaplan and A\&. Kovacs
.RE
.PP
SuperNOVAS planetary ephemeris manager for the planet_eph_manager and \fBplanet_eph_manager_hp()\fP functions\&.
.PP
This module exposes a lot of its own internal state variables globally\&. You probably should not access them from outside this module, but they are kept ad globals to ensure compatibility with existing NOVAS C applications that might access those values\&.
.PP
Based on the NOVAS C Edition, Version 3\&.1:
.PP
U\&. S\&. Naval Observatory
.br
 Astronomical Applications Dept\&.
.br
 Washington, DC
.br
 \fChttp://www\&.usno\&.navy\&.mil/USNO/astronomical-applications\fP
.PP
\fBSee also\fP
.RS 4
\fBsolsys2\&.c\fP 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "short ephem_close (void)"
Closes a JPL planetary ephemeris file and frees the memory\&.
.PP
REFERENCES: 
.PD 0
.IP "1." 4
Standish, E\&.M\&. and Newhall, X X (1988)\&. 'The JPL Export
    Planetary Ephemeris'; JPL document dated 17 June 1988\&. 
.PP
.PP
NOTES: 
.PD 0
.IP "1." 4
Includes fix for the known resource leak issue in NOVAS C 3\&.1\&. 
.PP
.PP
\fBReturns\fP
.RS 4
0 if the file successfully closed or was closed already, or else EOF\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBephem_open()\fP 
.RE
.PP

.PP
References \fBBUFFER\fP, and \fBEPHFILE\fP\&.
.SS "short ephem_open (const char * ephem_name, double * jd_begin, double * jd_end, short * de_number)"
This function opens a JPL planetary ephemeris file and sets initial values\&. This function must be called prior to calls to the other JPL ephemeris functions\&.
.PP
REFERENCES: 
.PD 0
.IP "1." 4
Standish, E\&.M\&. and Newhall, X X (1988)\&. 'The JPL Export Planetary Ephemeris'; JPL document dated 17 June 1988\&. 
.PP
.PP
\fBParameters\fP
.RS 4
\fIephem_name\fP Name/path of the direct-access ephemeris file\&. 
.br
\fIjd_begin\fP [day] Beginning Julian date of the ephemeris file\&. It may be NULL if not required\&. 
.br
\fIjd_end\fP [day] Ending Julian date of the ephemeris file\&. It may be NULL if not required\&. 
.br
\fIde_number\fP DE number of the ephemeris file opened\&. It may be NULL if not required\&.
.RE
.PP
\fBReturns\fP
.RS 4
0 if successful, or -1 if any of the arhuments is NULL, or else 1 if the file could no be opened, 2--10 if (= line + 1) if there was an error reading the header line, or 11 if the type of DE file is not supported\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBephem_close()\fP 
.RE
.PP

.PP
References \fBBUFFER\fP, \fBEM_RATIO\fP, \fBEPHFILE\fP, \fBIPT\fP, \fBJPLAU\fP, \fBKM\fP, \fBLPT\fP, \fBNP\fP, \fBNRL\fP, \fBNV\fP, \fBPC\fP, \fBRECORD_LENGTH\fP, \fBSS\fP, \fBTWOT\fP, and \fBVC\fP\&.
.SS "int interpolate (const double * buf, const double * t, long ncf, long na, double * position, double * velocity)"
Differentiates and interpolates a set of Chebyshev coefficients to give position and velocity\&.
.PP
REFERENCES: 
.PD 0
.IP "1." 4
Standish, E\&.M\&. and Newhall, X X (1988)\&. 'The JPL Export
    Planetary Ephemeris'; JPL document dated 17 June 1988\&. 
.PP
.PP
\fBParameters\fP
.RS 4
\fIbuf\fP Array of Chebyshev coefficients of position\&. 
.br
\fIt\fP t[0] is fractional time interval covered by coefficients at which interpolation is desired (0 <= t[0] <= 1)\&. t[1] is length of whole interval in input time units\&. 
.br
\fIncf\fP Number of coefficients per component\&. 
.br
\fIna\fP Number of sets of coefficients in full array (i\&.e\&., number of sub-intervals in full interval)\&. 
.br
\fIposition\fP Position array of requested object\&. 
.br
\fIvelocity\fP Velocity array of requested object\&.
.RE
.PP
\fBReturns\fP
.RS 4
0 if successful, or -1 if one of the input arrays or output pointer arguments is NULL\&. 
.RE
.PP

.PP
References \fBNP\fP, \fBNV\fP, \fBPC\fP, \fBTWOT\fP, and \fBVC\fP\&.
.SS "short planet_ephemeris (const double tjd[2], enum de_planet target, enum de_planet origin, double * position, double * velocity)"
Retries planet position and velocity data from the JPL planetary ephemeris
.PP
(If nutations are desired, set 'target' = 13; 'center' will be ignored on that call\&.)
.PP
REFERENCES: 
.PD 0
.IP "1." 4
Standish, E\&.M\&. and Newhall, X X (1988)\&. 'The JPL Export
    Planetary Ephemeris'; JPL document dated 17 June 1988\&. 
.PP
.PP
\fBParameters\fP
.RS 4
\fItjd\fP [day] Two-element array containing the Julian date, which may be split any way (although the first element is usually the 'integer' part, and the second element is the 'fractional' part)\&. Julian date is in the TDB or 'T_eph' time scale\&. 
.br
\fItarget\fP The integer code (see above) for the planet for which coordinates are requested, e\&.g\&. DE_JUPITER\&. 
.br
\fIorigin\fP The integer code of the planet or position relative to which coordinates are measured\&. 
.br
\fIposition\fP [AU] Position vector array of target relative to center, measured in AU\&. 
.br
\fIvelocity\fP [AU/day] Velocity vector array of target relative to center, measured in AU/day\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 if successful, or -1 if one of the pointer arguments is NULL, or else the error returned from \fBstate()\fP\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBephem_open()\fP 
.RE
.PP

.PP
References \fBEM_RATIO\fP, and \fBstate()\fP\&.
.SS "int split (double tt, double * fr)"
reaks up a double number into a double integer part and a fractional part\&.
.PP
\fBParameters\fP
.RS 4
\fItt\fP Input number\&. 
.br
\fIfr\fP 2-element output array; fr[0] contains integer part, fr[1] contains fractional part\&. For negative input numbers, fr[0] contains the next more negative integer; fr[1] contains a positive fraction\&.
.RE
.PP
\fBReturns\fP
.RS 4
0 if successful, or -1 if the output pointer argument is NULL\&. 
.RE
.PP

.SS "short state (const double * jed, enum de_planet target, double * target_pos, double * target_vel)"
Reads and interpolates the JPL planetary ephemeris file\&.
.PP
For ease in programming, the user may put the entire epoch in jed[0] and set jed[1] = 0\&. For maximum interpolation accuracy, set jed[0] = the most recent midnight at or before interpolation epoch, and set jed[1] = fractional part of a day elapsed between jed[0] and epoch\&. As an alternative, it may prove convenient to set jed[0] = some fixed epoch, such as start of the integration and jed[1] = elapsed interval between then and epoch\&.
.PP
REFERENCES: 
.PD 0
.IP "1." 4
Standish, E\&.M\&. and Newhall, X X (1988)\&. 'The JPL Export
    Planetary Ephemeris'; JPL document dated 17 June 1988\&. 
.PP
.PP
\fBParameters\fP
.RS 4
\fIjed\fP [day] 2-element Julian date (TDB) at which interpolation is wanted\&. Any combination of jed[0]+jed[1] which falls within the time span on the file is a permissible epoch\&. See Note 1 below\&. target (short) 
.br
\fItarget\fP The integer code (see above) for the planet for which coordinates are requested, e\&.g\&. DE_JUPITER\&. 
.br
\fItarget_pos\fP [AU] The barycentric position vector array of the requested object, in AU\&. 
.br
\fItarget_vel\fP [AU/day] The barycentric velocity vector array of the requested object, in AU/Day\&.
.RE
.PP
\fBReturns\fP
.RS 4
0 if successful, -1 if any of the pointer arguments is NULL, or else 1 if there was an error reading the ephemeris file, or 2 if the epoch is out of range\&. 
.RE
.PP

.PP
References \fBBUFFER\fP, \fBephem_close()\fP, \fBEPHFILE\fP, \fBinterpolate()\fP, \fBIPT\fP, \fBJPLAU\fP, \fBKM\fP, \fBNRL\fP, \fBRECORD_LENGTH\fP, \fBsplit()\fP, and \fBSS\fP\&.
.SH "Variable Documentation"
.PP 
.SS "short KM"

.PP
Flag that defines physical units of the output states\&. Flag that defines physical units of the output states\&. 1: km and km/sec; 0: AU and AU/day\&. Its default value is 0 (KM determines time unit for nutations\&. Angle unit is always radians\&.) 
.SH "Author"
.PP 
Generated automatically by Doxygen for SuperNOVAS from the source code\&.
