.TH "in_space" 3 "Version v1.2" "SuperNOVAS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
in_space
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <novas\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBsc_pos\fP [3]"
.br
.RI "[km] geocentric (or [AU] ICRS barycentric) position vector (x, y, z) "
.ti -1c
.RI "double \fBsc_vel\fP [3]"
.br
.RI "[km/s] geocentric (or [AU/day] ICRS barycentric) velocity vector (x_dot, y_dot, z_dot) "
.in -1c
.SH "Detailed Description"
.PP 
data for an observer's location on Earth orbit
.PP
\fBSee also\fP
.RS 4
\fBobserver\fP 
.PP
\fBIN_SPACE_INIT\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SuperNOVAS from the source code\&.
