.TH "md_CODE__OF__CONDUCT" 3Version v1.0" "SuperNOVAS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_CODE__OF__CONDUCT \- Contributor Covenant Code of Conduct 
.PP
 
.SH "Our Pledge"
.PP
We as members, contributors, and leaders pledge to make participation in our community a harassment-free experience for everyone, regardless of age, body size, visible or invisible disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation\&.
.PP
We pledge to act and interact in ways that contribute to an open, welcoming, diverse, inclusive, and healthy community\&.
.SH "Our Standards"
.PP
Examples of behavior that contributes to a positive environment for our community include:
.PP
.IP "\(bu" 2
Demonstrating empathy and kindness toward other people
.IP "\(bu" 2
Being respectful of differing opinions, viewpoints, and experiences
.IP "\(bu" 2
Giving and gracefully accepting constructive feedback
.IP "\(bu" 2
Accepting responsibility and apologizing to those affected by our mistakes, and learning from the experience
.IP "\(bu" 2
Focusing on what is best not just for us as individuals, but for the overall community
.PP
.PP
Examples of unacceptable behavior include:
.PP
.IP "\(bu" 2
The use of sexualized language or imagery, and sexual attention or advances of any kind
.IP "\(bu" 2
Trolling, insulting or derogatory comments, and personal or political attacks
.IP "\(bu" 2
Public or private harassment
.IP "\(bu" 2
Publishing others' private information, such as a physical or email address, without their explicit permission
.IP "\(bu" 2
Other conduct which could reasonably be considered inappropriate in a professional setting
.PP
.SH "Enforcement Responsibilities"
.PP
Community leaders are responsible for clarifying and enforcing our standards of acceptable behavior and will take appropriate and fair corrective action in response to any behavior that they deem inappropriate, threatening, offensive, or harmful\&.
.PP
Community leaders have the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned to this Code of Conduct, and will communicate reasons for moderation decisions when appropriate\&.
.SH "Scope"
.PP
This Code of Conduct applies within all community spaces, and also applies when an individual is officially representing the community in public spaces\&. Examples of representing our community include using an official e-mail address, posting via an official social media account, or acting as an appointed representative at an online or offline event\&.
.SH "Enforcement"
.PP
Instances of abusive, harassing, or otherwise unacceptable behavior may be reported to the community leaders responsible for enforcement at the Center for Astrophysics | Harvard & Smithsonian\&. All complaints will be reviewed and investigated promptly and fairly\&.
.PP
All community leaders are obligated to respect the privacy and security of the reporter of any incident\&.
.SH "Enforcement Guidelines"
.PP
Community leaders will follow these Community Impact Guidelines in determining the consequences for any action they deem in violation of this Code of Conduct:
.SS "1\&. Correction"
\fBCommunity Impact\fP: Use of inappropriate language or other behavior deemed unprofessional or unwelcome in the community\&.
.PP
\fBConsequence\fP: A private, written warning from community leaders, providing clarity around the nature of the violation and an explanation of why the behavior was inappropriate\&. A public apology may be requested\&.
.SS "2\&. Warning"
\fBCommunity Impact\fP: A violation through a single incident or series of actions\&.
.PP
\fBConsequence\fP: A warning with consequences for continued behavior\&. No interaction with the people involved, including unsolicited interaction with those enforcing the Code of Conduct, for a specified period of time\&. This includes avoiding interactions in community spaces as well as external channels like social media\&. Violating these terms may lead to a temporary or permanent ban\&.
.SS "3\&. Temporary Ban"
\fBCommunity Impact\fP: A serious violation of community standards, including sustained inappropriate behavior\&.
.PP
\fBConsequence\fP: A temporary ban from any sort of interaction or public communication with the community for a specified period of time\&. No public or private interaction with the people involved, including unsolicited interaction with those enforcing the Code of Conduct, is allowed during this period\&. Violating these terms may lead to a permanent ban\&.
.SS "4\&. Permanent Ban"
\fBCommunity Impact\fP: Demonstrating a pattern of violation of community standards, including sustained inappropriate behavior, harassment of an individual, or aggression toward or disparagement of classes of individuals\&.
.PP
\fBConsequence\fP: A permanent ban from any sort of public interaction within the community\&.
.SH "Attribution"
.PP
This Code of Conduct is adapted from the \fCContributor Covenant\fP, version 2\&.0, available at https://www.contributor-covenant.org/version/2/0/code_of_conduct.html\&.
.PP
Community Impact Guidelines were inspired by \fCMozilla's code of conduct enforcement ladder\fP\&.
.PP
For answers to common questions about this code of conduct, see the FAQ at https://www.contributor-covenant.org/faq\&. Translations are available at https://www.contributor-covenant.org/translations\&. 
