.TH "include/naif.h" 3 "Version v1.2" "SuperNOVAS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/naif.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNAIF_EARTH\fP   399"
.br
.RI "NAIF ID for the geocenter\&. "
.ti -1c
.RI "#define \fBNAIF_EMB\fP   3"
.br
.RI "NAIF ID for the Earth-Moon Barycenter (EMB) "
.ti -1c
.RI "#define \fBNAIF_MOON\fP   301"
.br
.RI "NAIF ID for the Moon\&. "
.ti -1c
.RI "#define \fBNAIF_SSB\fP   0"
.br
.RI "NAIF ID for the Solar-System Barycenter (SSB) "
.ti -1c
.RI "#define \fBNAIF_SUN\fP   10"
.br
.RI "NAIF_ID for the Sun\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBDate\fP
.RS 4
Created on Nov 6, 2024 
.RE
.PP
\fBAuthor\fP
.RS 4
Attila Kovacs 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperNOVAS from the source code\&.
