.TH "src/naif.c" 3 "Version v1.2" "SuperNOVAS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/naif.c
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__NOVAS_INTERNAL_API__\fP"
.br
.RI "Use definitions meant for internal use by SuperNOVAS only\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "enum \fBnovas_planet\fP \fBnaif_to_novas_planet\fP (long id)"
.br
.ti -1c
.RI "long \fBnovas_to_dexxx_planet\fP (enum \fBnovas_planet\fP id)"
.br
.ti -1c
.RI "long \fBnovas_to_naif_planet\fP (enum \fBnovas_planet\fP id)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBDate\fP
.RS 4
Created on Nov 6, 2024 
.RE
.PP
\fBAuthor\fP
.RS 4
Attila Kovacs
.RE
.PP
Solar system ID mappings between NOVAS and NASA's Navigation and Ancillary Information Facility (NAIF), which is used by the JPL ephemeris systems\&. The two differ for the numbering convention for major planets, the Sun, Moon, Solar-System Barycenter (SSB) and the Earth-Moon Barycenter (EMB)\&. NOVAS does not have predefined IDs beyond this set (and no defined ID for EMB), thus for all other objects we'll assume and use NOVAS IDs that match NAIF\&.
.PP
\fBSince\fP
.RS 4
1\&.2
.RE
.PP
\fBSee also\fP
.RS 4
\fBsolsys-calceph\&.c\fP 
.PP
\fBsolsys-cspice\&.c\fP 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "enum \fBnovas_planet\fP naif_to_novas_planet (long id)"
Converts a NAIF ID to a NOVAS major planet ID\&. It account for the different IDs used for Sun, Moon and SSB\&. Otherwise NAIF planet barycenters are mapped to the corresponding bodies, except EMB (3), which will return -1\&. NAIF body centers \fIn\fP99 (e\&.g\&. 399 for Earth), are mapped to the corresponding NOVAS planet number \fIn\fP\&. All other NAIF IDs will return -1, indicating no match to a NOVAS planet ID\&.
.PP
\fBParameters\fP
.RS 4
\fIid\fP The NAIF ID of the major planet of interest 
.RE
.PP
\fBReturns\fP
.RS 4
the NOVAS ID for the same object (which may or may not be different from the input), or -1 if the NAIF ID cannot be matched to a NOVAS major planet\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBnovas_to_naif_planet()\fP 
.PP
\fBnovas_to_dexxx_planet()\fP
.RE
.PP
\fBAuthor\fP
.RS 4
Attila Kovacs 
.RE
.PP
\fBSince\fP
.RS 4
1\&.2 
.RE
.PP

.PP
References \fBNOVAS_MERCURY\fP, \fBNOVAS_MOON\fP, \fBNOVAS_PLUTO\fP, \fBNOVAS_SSB\fP, and \fBNOVAS_SUN\fP\&.
.SS "long novas_to_dexxx_planet (enum \fBnovas_planet\fP id)"
Converts a NOVAS Solar-system body ID to a NAIF Solar-system body ID for DExxx ephemeris files\&. The DExxx (e\&.g\&. DE440) ephemeris files use NAIF IDs, but for most planets contain barycentric data only rather than that of the planet center\&. For Earth-based observations, it only really makes a difference whether the 3 is used for the Earth-Moon Barycenter (EMB) or 399 for the geocenter\&.
.PP
\fBParameters\fP
.RS 4
\fIid\fP The NOVAS ID of the major planet of interest 
.RE
.PP
\fBReturns\fP
.RS 4
the NAIF ID for the same object (which may or may not be different from the input), as appropriate for use in the DExxx ephemeris files\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBnovas_to_naif_planet()\fP 
.PP
\fBnaif_to_novas_planet()\fP
.RE
.PP
\fBAuthor\fP
.RS 4
Attila Kovacs 
.RE
.PP
\fBSince\fP
.RS 4
1\&.2 
.RE
.PP

.PP
References \fBNOVAS_EARTH\fP, \fBNOVAS_MERCURY\fP, \fBNOVAS_MOON\fP, \fBNOVAS_PLUTO\fP, \fBNOVAS_SSB\fP, and \fBNOVAS_SUN\fP\&.
.SS "long novas_to_naif_planet (enum \fBnovas_planet\fP id)"
Converts a NOVAS Solar-system body ID to a NAIF Solar-system body ID\&. NOVAS and NAIF use slightly different IDs for major planets, the Moon, and the Solar-system Barycenter (SSB)\&. In NOVAS, major planets are have IDs ranging from 1 through 9, but for NAIF 1--9 are the planetary barycenters and the planet centers have numbers in the hundreds ending with 99 (e\&.g\&. the center of Earth is NAIF 399; 3 is the NOVAS ID for Earth and the NAIF ID for the Earth-Moon Barycenter [EMB])\&. The Sun and Moon also have distinct IDs in NAIF vs NOVAS\&.
.PP
\fBParameters\fP
.RS 4
\fIid\fP The NOVAS ID of the major planet of interest 
.RE
.PP
\fBReturns\fP
.RS 4
the NAIF ID for the same object or planet center (which may or may not be different from the input)
.RE
.PP
\fBSee also\fP
.RS 4
\fBnaif_to_novas_planet()\fP
.RE
.PP
\fBAuthor\fP
.RS 4
Attila Kovacs 
.RE
.PP
\fBSince\fP
.RS 4
1\&.2 
.RE
.PP

.PP
References \fBNOVAS_MERCURY\fP, \fBNOVAS_MOON\fP, \fBNOVAS_PLUTO\fP, \fBNOVAS_SSB\fP, and \fBNOVAS_SUN\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SuperNOVAS from the source code\&.
