.TH "include/novascon.h" 3Version v1.0" "SuperNOVAS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/novascon.h
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const double \fBANGVEL\fP"
.br
.ti -1c
.RI "const double \fBAU\fP"
.br
.ti -1c
.RI "const double \fBAU_KM\fP"
.br
.ti -1c
.RI "const double \fBAU_SEC\fP"
.br
.ti -1c
.RI "const double \fBC\fP"
.br
.ti -1c
.RI "const double \fBC_AUDAY\fP"
.br
.ti -1c
.RI "const double \fBERAD\fP"
.br
.ti -1c
.RI "const double \fBF\fP"
.br
.ti -1c
.RI "const short \fBFN0\fP"
.br
.ti -1c
.RI "const short \fBFN1\fP"
.br
.ti -1c
.RI "const double \fBGE\fP"
.br
.ti -1c
.RI "const double \fBGS\fP"
.br
.ti -1c
.RI "const double \fBRMASS\fP [12]"
.br
.ti -1c
.RI "const double \fBT0\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
G\&. Kaplan and A\&. Kovacs
.RE
.PP
SuperNOVAS header for numerical constants that used to be used internally in \fBnovas\&.c\fP\&.
.PP
\fBDeprecated\fP
.RS 4
Use your own version for the selection of the constant you need, expressed in whatever units your application desires\&. We should not force you to adopt the internally used convention of NOVAS, not to mention the high chance of namespace conflicts with the super-simplistic naming scheme here\&. You are better off without this\&.
.RE
.PP
.PP
Based on the NOVAS C Edition, Version 3\&.1, U\&. S\&. Naval Observatory Astronomical Applications Dept\&. Washington, DC \fChttp://www\&.usno\&.navy\&.mil/USNO/astronomical-applications\fP 
.SH "Variable Documentation"
.PP 
.SS "const double ANGVEL\fC [extern]\fP"

.PP
\fBDeprecated\fP
.RS 4
Rotational angular velocity of Earth in radians/sec from IERS Conventions (2003)\&. Use NOVAS_EARTH_ANGVEL instead 
.RE
.PP

.SS "const double AU\fC [extern]\fP"

.PP
\fBDeprecated\fP
.RS 4
Astronomical unit in meters\&. Use NOVAS_AU instead\&. 
.RE
.PP

.SS "const double AU_KM\fC [extern]\fP"

.PP
\fBDeprecated\fP
.RS 4
Astronomical Unit in kilometers\&. Use NOVAS AU_KM instead\&. 
.RE
.PP

.SS "const double AU_SEC\fC [extern]\fP"

.PP
\fBDeprecated\fP
.RS 4
Light-time for one astronomical unit (AU) in seconds, from DE-405\&. Use NOVAS_AU_SEC instead\&. 
.RE
.PP

.SS "const double C\fC [extern]\fP"

.PP
\fBDeprecated\fP
.RS 4
Speed of light in meters/second is a defining physical constant\&. Use NOVAS_C instead\&. 
.RE
.PP

.SS "const double C_AUDAY\fC [extern]\fP"

.PP
\fBDeprecated\fP
.RS 4
Speed of light in AU/day\&. Use NOVAS_AUDAY instead\&. 
.RE
.PP

.SS "const double ERAD\fC [extern]\fP"

.PP
\fBDeprecated\fP
.RS 4
Radius of Earth in kilometers from IERS Conventions (2003)\&. Use NOVAS_EARTH_RADIUS instead 
.RE
.PP

.SS "const double F\fC [extern]\fP"

.PP
\fBDeprecated\fP
.RS 4
Earth ellipsoid flattening from IERS Conventions (2003)\&. Value is 1 / 298\&.25642\&. Use NOVAS_EARTH_FLATTENING instead\&. 
.RE
.PP

.SS "const short FN0\fC [extern]\fP"

.PP
\fBDeprecated\fP
.RS 4
Definition was already ommitted in NOVAS C 3\&.1\&. 
.RE
.PP

.SS "const short FN1\fC [extern]\fP"

.PP
\fBDeprecated\fP
.RS 4
Definition was already ommitted in NOVAS C 3\&.1\&. 
.RE
.PP

.SS "const double GE\fC [extern]\fP"

.PP
\fBDeprecated\fP
.RS 4
Geocentric gravitational constant in meters^3 / second^2, from DE-405\&. Use NOVAS_G_EARTH instead\&. 
.RE
.PP

.SS "const double GS\fC [extern]\fP"

.PP
\fBDeprecated\fP
.RS 4
Heliocentric gravitational constant in meters^3 / second^2, from DE-405\&. Use NOVAS_G_SUN instead\&. 
.RE
.PP

.SS "const double RMASS[12]\fC [extern]\fP"

.PP
\fBDeprecated\fP
.RS 4
Reciprocal masses of solar system bodies, from DE-405 (Sun mass / body mass)\&. MASS[0] = Earth/Moon barycenter, MASS[1] = Mercury, \&.\&.\&., MASS[9] = Pluto, MASS[10] = Sun, MASS[11] = Moon\&. Use NOVAS_RMASS_INIT instead\&. 
.RE
.PP

.SS "const double T0\fC [extern]\fP"

.PP
\fBDeprecated\fP
.RS 4
TDB Julian date of epoch J2000\&.0\&. Use NOVAS_JD_J2000 instead\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperNOVAS from the source code\&.
