.TH "novas_delaunay_args" 3 "Version v1.2" "SuperNOVAS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
novas_delaunay_args
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <novas\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBD\fP"
.br
.RI "[rad] mean elongation of the Moon from the Sun "
.ti -1c
.RI "double \fBF\fP"
.br
.RI "[rad] mean argument of the latitude of the Moon "
.ti -1c
.RI "double \fBl\fP"
.br
.RI "[rad] mean anomaly of the Moon "
.ti -1c
.RI "double \fBl1\fP"
.br
.RI "[rad] mean anomaly of the Sun "
.ti -1c
.RI "double \fBOmega\fP"
.br
.RI "[rad] mean longitude of the Moon's ascending node\&. "
.in -1c
.SH "Detailed Description"
.PP 
Fundamental Delaunay arguments of the Sun and Moon, from Simon section 3\&.4(b\&.3), precession = 5028\&.8200 arcsec/cy)
.PP
\fBSince\fP
.RS 4
1\&.0 
.RE
.PP
\fBAuthor\fP
.RS 4
Attila Kovacs 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SuperNOVAS from the source code\&.
