.TH "novas_track" 3 "Version v1.3" "SuperNOVAS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
novas_track
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <novas\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBnovas_observable\fP \fBaccel\fP"
.br
.RI "[deg/s\*{2\*} ,AU/s\*{2\*} ,1/s\*{2\*} ] Apparent position acceleration\&. "
.ti -1c
.RI "\fBnovas_observable\fP \fBpos\fP"
.br
.RI "[deg,AU,1] Apparent source position "
.ti -1c
.RI "\fBnovas_observable\fP \fBrate\fP"
.br
.RI "[deg/s,AU/s,1/s] Apparent position rate of change "
.ti -1c
.RI "\fBnovas_timespec\fP \fBtime\fP"
.br
.RI "The astronomical time for which the track is calculated\&. "
.in -1c
.SH "Detailed Description"
.PP 
The spherical and spectral tracking position of a source, and its first and second time derivatives\&. As such, it may be useful for telescope drive control (position, velocity, and acceleration), or else for fast extrapolation of momentary positions without a full, and costly, recalculation of the positions at high rate over a suitable short period\&.
.PP
\fBSince\fP
.RS 4
1\&.3 
.RE
.PP
\fBAuthor\fP
.RS 4
Attila Kovacs
.RE
.PP
\fBSee also\fP
.RS 4
\fBNOVAS_TRACK_INIT\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SuperNOVAS from the source code\&.
