.TH "novas_planet_bundle" 3 "Version v1.3" "SuperNOVAS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
novas_planet_bundle
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <novas\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBmask\fP"
.br
.RI "Bitwise mask (1 << planet-number) specifying wich planets have pos/vel data\&. "
.ti -1c
.RI "double \fBpos\fP [\fBNOVAS_PLANETS\fP][3]"
.br
.RI "[AU] Apparent positions of planets w\&.r\&.t\&. observer antedated for light-time "
.ti -1c
.RI "double \fBvel\fP [\fBNOVAS_PLANETS\fP][3]"
.br
.RI "[AU/day] Apparent velocity of planets w\&.r\&.t\&. barycenter antedated for light-time "
.in -1c
.SH "Detailed Description"
.PP 
Position and velocity data for a set of major planets (which may include the Sun and the Moon also)\&.
.PP
\fBSince\fP
.RS 4
1\&.1
.RE
.PP
\fBSee also\fP
.RS 4
enum \fBnovas_planet\fP 
.PP
\fBNOVAS_PLANET_BUNDLE_INIT\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SuperNOVAS from the source code\&.
