.TH "novas_observable" 3 "Version v1.3" "SuperNOVAS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
novas_observable
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <novas\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBdist\fP"
.br
.RI "[AU] apparent distance to source from observer "
.ti -1c
.RI "double \fBlat\fP"
.br
.RI "[deg] apparent latitude coordinate in coordinate system "
.ti -1c
.RI "double \fBlon\fP"
.br
.RI "[deg] apparent longitude coordinate in coordinate system "
.ti -1c
.RI "double \fBz\fP"
.br
.RI "redshift "
.in -1c
.SH "Detailed Description"
.PP 
Spherical and spectral coordinate set\&.
.PP
\fBSince\fP
.RS 4
1\&.3 
.RE
.PP
\fBAuthor\fP
.RS 4
Attila Kovacs
.RE
.PP
\fBSee also\fP
.RS 4
\fBnovas_track\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SuperNOVAS from the source code\&.
