.TH "src/nutation.c" 3 "Version v1.3" "SuperNOVAS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/nutation.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBiau2000a\fP (double jd_tt_high, double jd_tt_low, double *dpsi, double *deps)"
.br
.ti -1c
.RI "int \fBiau2000b\fP (double jd_tt_high, double jd_tt_low, double *dpsi, double *deps)"
.br
.ti -1c
.RI "int \fBnu2000k\fP (double jd_tt_high, double jd_tt_low, double *dpsi, double *deps)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
G\&. Kaplan and A\&. Kovacs
.RE
.PP
SuperNOVAS implementations for the IAU2000 nutation series calculations, with varying trade-offs between computational cost and precision\&. It provides support for both the IAU 2000A and IAU2000B series as well as a NOVAS-specific truncated low-precision version we call NU2000K\&.
.PP
Based on the NOVAS C Edition, Version 3\&.1:
.PP
U\&. S\&. Naval Observatory
.br
 Astronomical Applications Dept\&.
.br
 Washington, DC
.br
 \fChttp://www\&.usno\&.navy\&.mil/USNO/astronomical-applications\fP 
.SH "Function Documentation"
.PP 
.SS "int iau2000a (double jd_tt_high, double jd_tt_low, double * dpsi, double * deps)"
Computes the IAU 2000A nutation high-precision series for the specified date\&. It is rather expensive computationally\&.
.PP
The IAU 2000A nutation model is MHB_2000 without the free core nutation and without the corrections to Lieske precession\&.
.PP
REFERENCES: 
.PD 0
.IP "1." 4
IERS Conventions (2003), Chapter 5\&. 
.IP "2." 4
Simon et al\&. (1994) Astronomy and Astrophysics 282, 663-683, esp\&. Sections 3\&.4-3\&.5\&. 
.PP
.PP
\fBParameters\fP
.RS 4
\fIjd_tt_high\fP [day] High-order part of the Terrestrial Time (TT) based Julian date\&. Typically it may be the integer part of a split date for the highest precision, or the full date for normal (reduced) precision\&. 
.br
\fIjd_tt_low\fP [day] Low-order part of the Terrestrial Time (TT) based Julian date\&. Typically it may be the fractional part of a split date for the highest precision, or 0\&.0 for normal (reduced) precision\&. 
.br
\fIdpsi\fP [rad]  Nutation (luni-solar + planetary) in longitude, in radians\&. It may be NULL if not required\&. 
.br
\fIdeps\fP [rad]  Nutation (luni-solar + planetary) in obliquity, in radians\&. It may be NULL if not required\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0
.RE
.PP
\fBSee also\fP
.RS 4
\fBiau2000b()\fP 
.PP
\fBnu2000k()\fP 
.PP
\fBnutation_angles()\fP 
.PP
\fBnovas_nutation_provider\fP 
.RE
.PP

.PP
References \fBaccum_prec()\fP, \fBASEC2RAD\fP, \fBnovas_delaunay_args::D\fP, \fBnovas_delaunay_args::F\fP, \fBfund_args()\fP, \fBnovas_delaunay_args::l\fP, \fBnovas_delaunay_args::l1\fP, \fBNOVAS_EARTH\fP, \fBNOVAS_JUPITER\fP, \fBNOVAS_MARS\fP, \fBNOVAS_MERCURY\fP, \fBNOVAS_NEPTUNE\fP, \fBNOVAS_SATURN\fP, \fBNOVAS_URANUS\fP, \fBNOVAS_VENUS\fP, \fBnovas_delaunay_args::Omega\fP, \fBplanet_lon()\fP, and \fBT0\fP\&.
.SS "int iau2000b (double jd_tt_high, double jd_tt_low, double * dpsi, double * deps)"
Compute the forced nutation of the non-rigid Earth based on the IAU 2000B precession / nutation model\&.
.PP
IAU 2000B reproduces the IAU 2000A model to a precision of 1 milliarcsecond in the interval 1995-2020\&.
.PP
REFERENCES: 
.PD 0
.IP "1." 4
McCarthy, D\&. and Luzum, B\&. (2003)\&. 'An Abridged Model of the
    Precession & Nutation of the Celestial Pole,' Celestial Mechanics and Dynamical Astronomy, Volume 85, Issue 1, Jan\&. 2003, p\&. 37\&. (IAU 2000B) IERS Conventions (2003), Chapter 5\&. 
.PP
.PP
\fBParameters\fP
.RS 4
\fIjd_tt_high\fP [day] High-order part of the Terrestrial Time (TT) based Julian date\&. Typically it may be the integer part of a split date for the highest precision, or the full date for normal (reduced) precision\&. 
.br
\fIjd_tt_low\fP [day] Low-order part of the Terrestrial Time (TT) based Julian date\&. Typically it may be the fractional part of a split date for the highest precision, or 0\&.0 for normal (reduced) precision\&. 
.br
\fIdpsi\fP [rad]  Nutation (luni-solar + planetary) in longitude, in radians\&. It may be NULL if not required\&. 
.br
\fIdeps\fP [rad]  Nutation (luni-solar + planetary) in obliquity, in radians\&. It may be NULL if not required\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0
.RE
.PP
\fBSee also\fP
.RS 4
\fBiau2000a()\fP 
.PP
\fBnu2000k()\fP 
.PP
\fBset_nutation_lp_provider()\fP 
.PP
\fBnutation_angles()\fP 
.RE
.PP

.PP
References \fBASEC2RAD\fP, \fBnovas_delaunay_args::D\fP, \fBnovas_delaunay_args::F\fP, \fBfund_args()\fP, \fBnovas_delaunay_args::l\fP, \fBnovas_delaunay_args::l1\fP, \fBnovas_delaunay_args::Omega\fP, and \fBT0\fP\&.
.SS "int nu2000k (double jd_tt_high, double jd_tt_low, double * dpsi, double * deps)"
Computes the forced nutation of the non-rigid Earth: Model NU2000K\&. This model is a modified version of IAU 2000A, which has been truncated for speed of execution, and uses Simon et al\&. (1994) fundamental arguments throughout\&. NU2000K agrees with IAU 2000A at the 0\&.1 milliarcsecond level from 1700 to 2300\&. It has the most modest computational cost among the implementations provided in the NOVAS library\&.
.PP
NU2000K was compared to IAU 2000A over six centuries (1700-2300)\&. The average error in d is 20 microarcseconds, with 98% of the errors < 60 microarcseconds; the average error in dis 8 microarcseconds, with 100% of the errors < 60 microarcseconds\&.
.PP
NU2000K was developed by G\&. Kaplan (USNO) in March 2004
.PP
REFERENCES: 
.PD 0
.IP "1." 4
IERS Conventions (2003), Chapter 5\&. 
.IP "2." 4
Simon et al\&. (1994) Astronomy and Astrophysics 282, 663-683, esp\&. Sections 3\&.4-3\&.5\&. 
.PP
.PP
\fBParameters\fP
.RS 4
\fIjd_tt_high\fP [day] High-order part of the Terrestrial Time (TT) based Julian date\&. Typically it may be the integer part of a split date for the highest precision, or the full date for normal (reduced) precision\&. 
.br
\fIjd_tt_low\fP [day] Low-order part of the Terrestrial Time (TT) based Julian date\&. Typically it may be the fractional part of a split date for the highest precision, or 0\&.0 for normal (reduced) precision\&. 
.br
\fIdpsi\fP [rad]  Nutation (luni-solar + planetary) in longitude, in radians\&. It may be NULL if not required\&. 
.br
\fIdeps\fP [rad]  Nutation (luni-solar + planetary) in obliquity, in radians\&. It may be NULL if not required\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0
.RE
.PP
\fBSee also\fP
.RS 4
\fBiau2000a()\fP 
.PP
\fBiau2000b()\fP 
.PP
\fBnutation_angles()\fP 
.PP
\fBnovas_nutation_provider\fP 
.RE
.PP

.PP
References \fBaccum_prec()\fP, \fBASEC2RAD\fP, \fBnovas_delaunay_args::D\fP, \fBnovas_delaunay_args::F\fP, \fBfund_args()\fP, \fBnovas_delaunay_args::l\fP, \fBnovas_delaunay_args::l1\fP, \fBNOVAS_EARTH\fP, \fBNOVAS_JUPITER\fP, \fBNOVAS_MARS\fP, \fBNOVAS_SATURN\fP, \fBNOVAS_VENUS\fP, \fBnovas_delaunay_args::Omega\fP, \fBplanet_lon()\fP, and \fBT0\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SuperNOVAS from the source code\&.
