.TH "object" 3 "Version v1.3" "SuperNOVAS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
object
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <novas\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP [\fBSIZE_OF_OBJ_NAME\fP]"
.br
.RI "name of the object (0-terminated) "
.ti -1c
.RI "long \fBnumber\fP"
.br
.RI "enum novas_planet, or minor planet ID (e\&.g\&. NAIF), or star catalog ID\&. "
.ti -1c
.RI "\fBnovas_orbital\fP \fBorbit\fP"
.br
.RI "orbital data for NOVAS_ORBITAL_OBJECT type\&. "
.ti -1c
.RI "\fBcat_entry\fP \fBstar\fP"
.br
.RI "basic astrometric data for NOVAS_CATALOG_OBJECT type\&. "
.ti -1c
.RI "enum \fBnovas_object_type\fP \fBtype\fP"
.br
.RI "NOVAS object type\&. "
.in -1c
.SH "Detailed Description"
.PP 
Celestial object of interest\&.
.PP
Note, the memory footprint is different from NOVAS C due to the use of the enum vs short 'type' and the long vs\&. short 'number' values -- hence it is not cross-compatible for binary data exchange with NOVAS C 3\&.1\&.
.PP
\fBSee also\fP
.RS 4
\fBNOVAS_OBJECT_INIT\fP 
.PP
\fBNOVAS_MERCURY_INIT\fP 
.PP
\fBNOVAS_VENUS_INIT\fP 
.PP
\fBNOVAS_EARTH_INIT\fP 
.PP
\fBNOVAS_MARS_INIT\fP 
.PP
\fBNOVAS_JUPITER_INIT\fP 
.PP
\fBNOVAS_SATURN_INIT\fP 
.PP
\fBNOVAS_URANUS_INIT\fP 
.PP
\fBNOVAS_NEPTUNE_INIT\fP 
.PP
\fBNOVAS_PLUTO_INIT\fP 
.PP
\fBNOVAS_PLUTO_BARYCENTER_INIT\fP 
.PP
\fBNOVAS_SUN_INIT\fP 
.PP
\fBNOVAS_SSB_INIT\fP 
.PP
\fBNOVAS_MOON_INIT\fP 
.PP
\fBNOVAS_EMB_INIT\fP 
.RE
.PP

.SH "Field Documentation"
.PP 
.SS "\fBnovas_orbital\fP orbit"

.PP
orbital data for NOVAS_ORBITAL_OBJECT type\&. 
.PP
\fBSince\fP
.RS 4
1\&.2 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SuperNOVAS from the source code\&.
