.TH "on_surface" 3 "Version v1.3" "SuperNOVAS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
on_surface
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <novas\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBheight\fP"
.br
.RI "[m] altitude above sea level "
.ti -1c
.RI "double \fBhumidity\fP"
.br
.RI "[%] Relative humidity\&. "
.ti -1c
.RI "double \fBlatitude\fP"
.br
.RI "[deg] geodetic (ITRS) latitude; north positive "
.ti -1c
.RI "double \fBlongitude\fP"
.br
.RI "[deg] geodetic (ITRS) longitude; east positive "
.ti -1c
.RI "double \fBpressure\fP"
.br
.RI "[mbar] atmospheric pressure for optical refraction "
.ti -1c
.RI "double \fBtemperature\fP"
.br
.RI "[C] temperature (degrees Celsius); for optical refraction "
.in -1c
.SH "Detailed Description"
.PP 
Data for an observer's location on the surface of the Earth, and optional local weather data for refraction calculations only\&.
.PP
\fBSee also\fP
.RS 4
\fBobserver\fP 
.PP
\fBmake_on_surface()\fP 
.PP
\fBON_SURFACE_INIT\fP 
.PP
\fBON_SURFACE_LOC\fP 
.RE
.PP

.SH "Field Documentation"
.PP 
.SS "double humidity"

.PP
[%] Relative humidity\&. 
.PP
\fBSince\fP
.RS 4
1\&.1 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SuperNOVAS from the source code\&.
