.TH "ra_of_cio" 3 "Mon Mar 4 2024" "Version v1.0" "SuperNOVAS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ra_of_cio
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBjd_tdb\fP"
.br
.RI "[day] Barycentric Dynamical Time (TDB) based Julian date\&. "
.ti -1c
.RI "double \fBra_cio\fP"
.br
.RI "[arcsec] right ascension of the CIO with respect to the GCRS (arcseconds) "
.in -1c
.SH "Detailed Description"
.PP 
Right ascension of the Celestial Intermediate Origin (CIO) with respect to the GCRS 

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperNOVAS from the source code\&.
