.TH "sky_pos" 3 "Version v1.2" "SuperNOVAS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sky_pos
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <novas\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBdec\fP"
.br
.RI "[deg] apparent, topocentric, or astrometric declination (degrees) "
.ti -1c
.RI "double \fBdis\fP"
.br
.RI "[AU] true (geometric, Euclidian) distance to solar system body or 0\&.0 for star (AU) "
.ti -1c
.RI "double \fBr_hat\fP [3]"
.br
.RI "unit vector toward object (dimensionless) "
.ti -1c
.RI "double \fBra\fP"
.br
.RI "[h] apparent, topocentric, or astrometric right ascension (hours) "
.ti -1c
.RI "double \fBrv\fP"
.br
.RI "[km/s] radial velocity (km/s) "
.in -1c
.SH "Detailed Description"
.PP 
Celestial object's place on the sky; contains the output from \fBplace()\fP
.PP
\fBSee also\fP
.RS 4
\fBplace()\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SuperNOVAS from the source code\&.
