.TH "src/solsys-calceph.c" 3 "Version v1.3" "SuperNOVAS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/solsys-calceph.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBnovas_calceph_use_ids\fP (enum \fBnovas_id_type\fP idtype)"
.br
.ti -1c
.RI "int \fBnovas_use_calceph\fP (t_calcephbin *eph)"
.br
.ti -1c
.RI "int \fBnovas_use_calceph_planets\fP (t_calcephbin *eph)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
A\&. Kovacs 
.RE
.PP
\fBSince\fP
.RS 4
1\&.2
.RE
.PP
SuperNOVAS Solar-system ephemeris lookup implementation via the CALCEPH C library\&.
.PP
This is an optional component of SuperNOVAS, which interfaces to the CALCEPH C library\&. As such, you may need the CALCEPH runtime libraries in an accessible location (such as in \fC/usr/lib\fP) to use, and you will need development files (C headers and unversioned libraries) to build\&. Thus, this module is compiled only if \fCCALCEPH_SUPPORT\fP is set to 1 prior to the build\&.
.PP
REFERENCES: 
.PD 0
.IP "1." 4
CALCEPH is at https://calceph.imcce.fr/docs/4.0.0/html/c/ 
.IP "2." 4
CALCEPH source code is at https://gitlab.obspm.fr/imcce_calceph/calceph 
.PP
.PP
\fBSee also\fP
.RS 4
\fBsolarsystem\&.h\fP 
.PP
\fBsolsys-cspice\&.c\fP 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int novas_calceph_use_ids (enum \fBnovas_id_type\fP idtype)"
Sets the type of Solar-system body IDs to use as \fBobject\&.number\fP with NOVAS_EPHEM_OBJECT types\&. CALCEPH supports the use of both NAIF and its own numbering system to identify Solar-system bodies\&. So, this function gives you the choice on which numbering system you want to use in object data structures\&. The choice does not affect major planets (which always use the NOVAS numbering scheme), or catalog objects\&.
.PP
\fBParameters\fP
.RS 4
\fIidtype\fP NOVAS_ID_NAIF to use NAIF IDs (default) or else NOVAS_ID_CALCEPH to use the CALCEPH body numbering convention for object\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 if successful or else -1 (errno set to EINVAL) if the input value is invalid\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBobject\fP 
.PP
\fBNOVAS_EPHEM_OBJECT\fP 
.RE
.PP

.PP
References \fBNOVAS_ID_CALCEPH\fP, and \fBNOVAS_ID_NAIF\fP\&.
.SS "int novas_use_calceph (t_calcephbin * eph)"
Sets a ephemeris provider for Solar-system objects using the CALCEPH C library and the specified set of ephemeris files\&. If the supplied ephemeris files contain data for major planets also, they can be used by planet_calceph() / planet_calceph_hp() also, unless a separate CALCEPH ephemeris data is set via \fBnovas_use_calceph_planets()\fP\&.
.PP
The call also make CALCEPH the default ephemeris provider for all types of Solar-system objects\&. If you want to use another provider for major planets, you need to call \fBset_planet_provider()\fP / \fBset_planet_provider_hp()\fP afterwards to specify a different provider for major planets (and Sun, Moon, SSB\&.\&.\&.)\&.
.PP
\fBParameters\fP
.RS 4
\fIeph\fP Pointer to the CALCEPH ephemeris data that have been opened\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 if successful, or else -1 (errno will indicate the type of error)\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBnovas_calceph_use_ids()\fP 
.PP
\fBnovas_use_calceph_planets()\fP 
.PP
\fBset_ephem_provider()\fP
.RE
.PP
\fBAuthor\fP
.RS 4
Attila Kovacs 
.RE
.PP
\fBSince\fP
.RS 4
1\&.2 
.RE
.PP

.PP
References \fBnovas_use_calceph_planets()\fP, and \fBset_ephem_provider()\fP\&.
.SS "int novas_use_calceph_planets (t_calcephbin * eph)"
Sets the CALCEPH C library and the specified ephemeris data as the ephemeris provider for the major planets (and Sun, Moon, SSB\&.\&.\&.)\&.
.PP
\fBParameters\fP
.RS 4
\fIeph\fP Pointer to the CALCEPH ephemeris data for the major planets (including Sun, Moon, SSB\&.\&.\&.) that have been opened\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 if successful, or else -1 (errno will indicate the type of error)\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBnovas_use_calceph()\fP 
.PP
\fBset_planet_provider()\fP 
.PP
\fBset_planet_provider_hp()\fP
.RE
.PP
\fBAuthor\fP
.RS 4
Attila Kovacs 
.RE
.PP
\fBSince\fP
.RS 4
1\&.2 
.RE
.PP

.PP
References \fBset_planet_provider()\fP, and \fBset_planet_provider_hp()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SuperNOVAS from the source code\&.
