.TH "src/spectral.c" 3 "Version v1.3" "SuperNOVAS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/spectral.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBnovas_lsr_to_ssb_vel\fP (double epoch, double ra, double dec, double vLSR)"
.br
.ti -1c
.RI "double \fBnovas_ssb_to_lsr_vel\fP (double epoch, double ra, double dec, double vLSR)"
.br
.ti -1c
.RI "double \fBnovas_v2z\fP (double vel)"
.br
.ti -1c
.RI "double \fBnovas_z2v\fP (double z)"
.br
.RI "========================================================================== "
.ti -1c
.RI "double \fBnovas_z_add\fP (double z1, double z2)"
.br
.ti -1c
.RI "double \fBnovas_z_inv\fP (double z)"
.br
.ti -1c
.RI "int \fBrad_vel\fP (const \fBobject\fP *restrict source, const double *restrict pos_src, const double *vel_src, const double *vel_obs, double d_obs_geo, double d_obs_sun, double d_src_sun, double *restrict rv)"
.br
.ti -1c
.RI "double \fBrad_vel2\fP (const \fBobject\fP *restrict source, const double *pos_emit, const double *vel_src, const double *pos_det, const double *vel_obs, double d_obs_geo, double d_obs_sun, double d_src_sun)"
.br
.ti -1c
.RI "double \fBredshift_vrad\fP (double vrad, double z)"
.br
.ti -1c
.RI "double \fBunredshift_vrad\fP (double vrad, double z)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBDate\fP
.RS 4
Created on Mar 5, 2025 
.RE
.PP
\fBAuthor\fP
.RS 4
Attila Kovacs
.RE
.PP
Various spectral / velocity related extensions to novas\&.c 
.SH "Function Documentation"
.PP 
.SS "double novas_lsr_to_ssb_vel (double epoch, double ra, double dec, double vLSR)"
Returns a Solar System Baricentric (SSB) radial velocity for a radial velocity that is referenced to the Local Standard of Rest (LSR)\&. Internally, NOVAS always uses barycentric radial velocities, but it is just as common to have catalogs define radial velocities referenced to the LSR\&.
.PP
The SSB motion w\&.r\&.t\&. the barycenter is assumed to be (11\&.1, 12\&.24, 7\&.25) km/s in ICRS (Shoenrich et al\&. 2010)\&.
.PP
REFERENCES: 
.PD 0
.IP "1." 4
Ralph Schoenrich, James Binney, Walter Dehnen, Monthly Notices of the Royal Astronomical Society, Volume 403, Issue 4, April 2010, Pages 1829–1833, https://doi.org/10.1111/j.1365-2966.2010.16253.x 
.PP
.PP
\fBParameters\fP
.RS 4
\fIepoch\fP [yr] Coordinate epoch in which the coordinates and velocities are defined\&. E\&.g\&. 2000\&.0\&. 
.br
\fIra\fP [h] Right-ascenscion of source at given epoch\&. 
.br
\fIdec\fP [deg] Declination of source at given epoch\&. 
.br
\fIvLSR\fP [km/s] radial velocity defined against the Local Standard of Rest (LSR), at given epoch\&.
.RE
.PP
\fBReturns\fP
.RS 4
[km/s] Equivalent Solar-System Barycentric radial velocity\&.
.RE
.PP
\fBSince\fP
.RS 4
1\&.3 
.RE
.PP
\fBAuthor\fP
.RS 4
Attila Kovacs
.RE
.PP
\fBSee also\fP
.RS 4
\fBmake_cat_entry()\fP 
.PP
\fBnovas_ssb_to_lsr_vel()\fP 
.RE
.PP

.PP
References \fBNOVAS_JD_J2000\fP, \fBprecession()\fP, and \fBradec2vector()\fP\&.
.SS "double novas_ssb_to_lsr_vel (double epoch, double ra, double dec, double vLSR)"
Returns a radial-velocity referenced to the Local Standard of Rest (LSR) for a given Solar-System Barycentric (SSB) radial velocity\&. Internally, NOVAS always uses barycentric radial velocities, but it is just as common to have catalogs define radial velocities referenced to the LSR\&.
.PP
The SSB motion w\&.r\&.t\&. the barycenter is assumed to be (11\&.1, 12\&.24, 7\&.25) km/s in ICRS (Shoenrich et al\&. 2010)\&.
.PP
REFERENCES: 
.PD 0
.IP "1." 4
Ralph Schoenrich, James Binney, Walter Dehnen, Monthly Notices of the Royal Astronomical Society, Volume 403, Issue 4, April 2010, Pages 1829–1833, https://doi.org/10.1111/j.1365-2966.2010.16253.x 
.PP
.PP
\fBParameters\fP
.RS 4
\fIepoch\fP [yr] Coordinate epoch in which the coordinates and velocities are defined\&. E\&.g\&. 2000\&.0\&. 
.br
\fIra\fP [h] Right-ascenscion of source at given epoch\&. 
.br
\fIdec\fP [deg] Declination of source at given epoch\&. 
.br
\fIvLSR\fP [km/s] radial velocity defined against the Local Standard of Rest (LSR), at given epoch\&.
.RE
.PP
\fBReturns\fP
.RS 4
[km/s] Equivalent Solar-System Barycentric radial velocity\&.
.RE
.PP
\fBSince\fP
.RS 4
1\&.3 
.RE
.PP
\fBAuthor\fP
.RS 4
Attila Kovacs
.RE
.PP
\fBSee also\fP
.RS 4
\fBmake_cat_entry()\fP 
.PP
\fBnovas_lsr_to_ssb_vel()\fP 
.RE
.PP

.PP
References \fBNOVAS_JD_J2000\fP, \fBprecession()\fP, and \fBradec2vector()\fP\&.
.SS "double novas_v2z (double vel)"
Converts a radial recession velocity to a redshift value (z = f / f\*<rest\*> )\&. It is based on the relativistic formula: 
.PP
.nf

 1 + z = sqrt((1 + ) / (1 - ))
.fi
.PP
 where  = v / c\&.
.PP
\fBParameters\fP
.RS 4
\fIvel\fP [km/s] velocity (i\&.e\&. rate) of recession\&. 
.RE
.PP
\fBReturns\fP
.RS 4
the corresponding redshift value ( / \*<rest\*> ), or NAN if the input velocity is invalid (i\&.e\&., it exceeds the speed of light)\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBnovas_z2v()\fP 
.PP
\fBnovas_z_add()\fP
.RE
.PP
\fBAuthor\fP
.RS 4
Attila Kovacs 
.RE
.PP
\fBSince\fP
.RS 4
1\&.2 
.RE
.PP

.PP
References \fBNOVAS_KMS\fP\&.
.SS "double novas_z2v (double z)"

.PP
========================================================================== Converts a redshift value (z = f / f\*<rest\*> ) to a radial velocity (i\&.e\&. rate) of recession\&. It is based on the relativistic formula: 
.PP
.nf

 1 + z = sqrt((1 + ) / (1 - ))
.fi
.PP
 where  = v / c\&.
.PP
\fBParameters\fP
.RS 4
\fIz\fP the redshift value ( / \*<rest\*> )\&. 
.RE
.PP
\fBReturns\fP
.RS 4
[km/s] Corresponding velocity of recession, or NAN if the input redshift is invalid, i\&.e\&. z <= -1)\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBnovas_v2z()\fP 
.PP
\fBredshift_vrad()\fP
.RE
.PP
\fBAuthor\fP
.RS 4
Attila Kovacs 
.RE
.PP
\fBSince\fP
.RS 4
1\&.2 
.RE
.PP

.PP
References \fBNOVAS_KMS\fP\&.
.SS "double novas_z_add (double z1, double z2)"
Compounds two redshift corrections, e\&.g\&. to apply (or undo) a series gravitational redshift corrections and/or corrections for a moving observer\&. It's effectively using (1 + z) = (1 + z1) * (1 + z2)\&.
.PP
\fBParameters\fP
.RS 4
\fIz1\fP One of the redshift values 
.br
\fIz2\fP The other redshift value 
.RE
.PP
\fBReturns\fP
.RS 4
The compound redshift value, ot NAN if either input redshift is invalid (errno will be set to EINVAL)\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBgrav_redshift()\fP 
.PP
\fBredshift_vrad()\fP 
.PP
\fBunredshift_vrad()\fP
.RE
.PP
\fBSince\fP
.RS 4
1\&.2 
.RE
.PP
\fBAuthor\fP
.RS 4
Attila Kovacs 
.RE
.PP

.SS "double novas_z_inv (double z)"
Returns the inverse of a redshift value, that is the redshift for a body moving with the same velocity as the original but in the opposite direction\&.
.PP
\fBParameters\fP
.RS 4
\fIz\fP A redhift value 
.RE
.PP
\fBReturns\fP
.RS 4
The redshift value for a body moving in the opposite direction with the same speed, or NAN if the input redshift is invalid\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBnovas_z_add()\fP
.RE
.PP
\fBSince\fP
.RS 4
1\&.2 
.RE
.PP
\fBAuthor\fP
.RS 4
Attila Kovacs 
.RE
.PP

.SS "int rad_vel (const \fBobject\fP *restrict source, const double *restrict pos_src, const double * vel_src, const double * vel_obs, double d_obs_geo, double d_obs_sun, double d_src_sun, double *restrict rv)"
Predicts the radial velocity of the observed object as it would be measured by spectroscopic means\&. Radial velocity is here defined as the radial velocity measure (z) times the speed of light\&. For major planets (and Sun and Moon), it includes gravitational corrections for light originating at the surface and observed from near Earth or else from a large distance away\&. For other solar system bodies, it applies to a fictitious emitter at the center of the observed object, assumed massless (no gravitational red shift)\&. The corrections do not in general apply to reflected light\&. For stars, it includes all effects, such as gravitational redshift, contained in the catalog barycentric radial velocity measure, a scalar derived from spectroscopy\&. Nearby stars with a known kinematic velocity vector (obtained independently of spectroscopy) can be treated like solar system objects\&.
.PP
Gravitational blueshift corrections for the Solar and Earth potential for observers are included\&. However, the result does not include a blueshift correction for observers (e\&.g\&. spacecraft) orbiting other major Solar-system bodies\&. You may adjust the amount of gravitational redshift correction applied to the radial velocity via \fC\fBredshift_vrad()\fP\fP, \fC\fBunredshift_vrad()\fP\fP and \fC\fBgrav_redshift()\fP\fP if necessary\&.
.PP
All the input arguments are BCRS quantities, expressed with respect to the ICRS axes\&. 'vel_src' and 'vel_obs' are kinematic velocities - derived from geometry or dynamics, not spectroscopy\&.
.PP
If the object is outside the solar system, the algorithm used will be consistent with the IAU definition of stellar radial velocity, specifically, the barycentric radial velocity measure, which is derived from spectroscopy\&. In that case, the vector 'vel_src' can be very approximate -- or, for distant stars or galaxies, zero -- as it will be used only for a small geometric correction that is proportional to proper motion\&.
.PP
Any of the distances (last three input arguments) can be set to zero (0\&.0) or negative if the corresponding general relativistic gravitational potential term is not to be evaluated\&. These terms generally are important at the meter/second level only\&. If 'd_obs_geo' and 'd_obs_sun' are both zero, an average value will be used for the relativistic term for the observer, appropriate for an observer on the surface of the Earth\&. 'd_src_sun', if given, is used only for solar system objects\&.
.PP
NOTES: 
.PD 0
.IP "1." 4
This function does not accont for the gravitational deflection of Solar-system sources\&. For that purpose, the \fBrad_vel2()\fP function, introduced in v1\&.1, is more appropriate\&. 
.IP "2." 4
The NOVAS C implementation did not include relatistic corrections for a moving observer if both \fCd_obs_geo\fP and \fCd_obs_sun\fP were zero\&. As of SuperNOVAS v1\&.1, the relatistic corrections for a moving observer will be included in the radial velocity measure always\&. 
.IP "3." 4
In a departure from the original NOVAS C, the radial velocity for major planets (and Sun and Moon) includes gravitational redshift corrections for light originating at the surface, assuming it's observed from near Earth or else from a large distance away\&. 
.PP
.PP
REFERENCES: 
.PD 0
.IP "1." 4
Lindegren & Dravins (2003), Astronomy & Astrophysics 401, 1185-1201\&. 
.IP "2." 4
Unlike NOVAS C, this function will return a radial velocity for the Sun that is gravitationally referenced to the Sun's photosphere\&. (NOVAS C returns the radial velocity for a massless Sun) 
.PP
.PP
\fBParameters\fP
.RS 4
\fIsource\fP Celestial object observed 
.br
\fIpos_src\fP [AU|*] Geometric position vector of object with respect to observer\&. For solar system sources it should be corrected for light-time\&. For non-solar-system objects, the position vector defines a direction only, with arbitrary magnitude\&. 
.br
\fIvel_src\fP [AU/day] Velocity vector of object with respect to solar system barycenter\&. 
.br
\fIvel_obs\fP [AU/day] Velocity vector of observer with respect to solar system barycenter\&. 
.br
\fId_obs_geo\fP [AU] Distance from observer to geocenter, or <=0\&.0 if gravitational blueshifting due to Earth potential around observer can be ignored\&. 
.br
\fId_obs_sun\fP [AU] Distance from observer to Sun, or <=0\&.0 if gravitational bluehifting due to Solar potential around observer can be ignored\&. 
.br
\fId_src_sun\fP [AU] Distance from object to Sun, or <=0\&.0 if gravitational redshifting due to Solar potential around source can be ignored\&. 
.br
\fIrv\fP [km/s] The observed radial velocity measure times the speed of light, or NAN if there was an error\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 if successfule, or else -1 if there was an error (errno will be set to EINVAL if any of the arguments are NULL, or to some other value to indicate the type of error)\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBrad_vel2()\fP 
.RE
.PP

.PP
References \fBrad_vel2()\fP\&.
.SS "double rad_vel2 (const \fBobject\fP *restrict source, const double * pos_emit, const double * vel_src, const double * pos_det, const double * vel_obs, double d_obs_geo, double d_obs_sun, double d_src_sun)"
Predicts the radial velocity of the observed object as it would be measured by spectroscopic means\&. This is a modified version of the original NOVAS C 3\&.1 \fBrad_vel()\fP, to account for the different directions in which light is emitted vs in which it detected, e\&.g\&. when it is gravitationally deflected\&.
.PP
Radial velocity is here defined as the radial velocity measure (z) times the speed of light\&. For major planets (and Sun and Moon), it includes gravitational corrections for light originating at the surface and observed from near Earth or else from a large distance away\&. For other solar system bodies, it applies to a fictitious emitter at the center of the observed object, assumed massless (no gravitational red shift)\&. The corrections do not in general apply to reflected light\&. For stars, it includes all effects, such as gravitational redshift, contained in the catalog barycentric radial velocity measure, a scalar derived from spectroscopy\&. Nearby stars with a known kinematic velocity vector (obtained independently of spectroscopy) can be treated like solar system objects\&.
.PP
Gravitational blueshift corrections for the Solar and Earth potential for observers are included\&. However, the result does not include a blueshift correction for observers (e\&.g\&. spacecraft) orbiting other major Solar-system bodies\&. You may adjust the amount of gravitational redshift correction applied to the radial velocity via \fC\fBredshift_vrad()\fP\fP, \fC\fBunredshift_vrad()\fP\fP and \fC\fBgrav_redshift()\fP\fP if necessary\&.
.PP
All the input arguments are BCRS quantities, expressed with respect to the ICRS axes\&. 'vel_src' and 'vel_obs' are kinematic velocities - derived from geometry or dynamics, not spectroscopy\&.
.PP
If the object is outside the solar system, the algorithm used will be consistent with the IAU definition of stellar radial velocity, specifically, the barycentric radial velocity measure, which is derived from spectroscopy\&. In that case, the vector 'vel_src' can be very approximate -- or, for distant stars or galaxies, zero -- as it will be used only for a small geometric and relativistic (time dilation) correction, including the proper motion\&.
.PP
Any of the distances (last three input arguments) can be set to a negative value if the corresponding general relativistic gravitational potential term is not to be evaluated\&. These terms generally are important only at the meter/second level\&. If 'd_obs_geo' and 'd_obs_sun' are both zero, an average value will be used for the relativistic term for the observer, appropriate for an observer on the surface of the Earth\&. 'd_src_sun', if given, is used only for solar system objects\&.
.PP
NOTES: 
.PD 0
.IP "1." 4
This function is called by \fBplace()\fP and \fBnovas_sky_pos()\fP to calculate radial velocities along with the apparent position of the source\&. 
.IP "2." 4
For major planets (and Sun and Moon), the radial velocity includes gravitational redshift corrections for light originating at the surface, assuming it's observed from near Earth or else from a large distance away\&. 
.PP
.PP
REFERENCES: 
.PD 0
.IP "1." 4
Lindegren & Dravins (2003), Astronomy & Astrophysics 401, 1185-1201\&. 
.PP
.PP
\fBParameters\fP
.RS 4
\fIsource\fP Celestial object observed 
.br
\fIpos_emit\fP [AU|*] position vector of object with respect to observer in the direction that light was emitted from the source\&. For solar system sources it should be corrected for light-time\&. For non-solar-system objects, the position vector defines a direction only, with arbitrary magnitude\&. 
.br
\fIvel_src\fP [AU/day] Velocity vector of object with respect to solar system barycenter\&. 
.br
\fIpos_det\fP [AU|*] apparent position vector of source, as seen by the observer\&. It may be the same vector as \fCpos_emit\fP, in which case the routine behaves like the original NOVAS_C \fBrad_vel()\fP\&. 
.br
\fIvel_obs\fP [AU/day] Velocity vector of observer with respect to solar system barycenter\&. 
.br
\fId_obs_geo\fP [AU] Distance from observer to geocenter, or <=0\&.0 if gravitational blueshifting due to Earth potential around observer can be ignored\&. 
.br
\fId_obs_sun\fP [AU] Distance from observer to Sun, or <=0\&.0 if gravitational bluehifting due to Solar potential around observer can be ignored\&. 
.br
\fId_src_sun\fP [AU] Distance from object to Sun, or <=0\&.0 if gravitational redshifting due to Solar potential around source can be ignored\&. Additionally, a value <0 will also skip corrections for light originating at the surface of the observed major solar-system body\&. 
.RE
.PP
\fBReturns\fP
.RS 4
[km/s] The observed radial velocity measure times the speed of light, or NAN if there was an error (errno will be set to EINVAL if any of the arguments are NULL, or to some other value to indicate the type of error)\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBrad_vel()\fP 
.PP
\fBplace()\fP 
.PP
\fBnovas_sky_pos()\fP 
.PP
\fBnovas_v2z()\fP
.RE
.PP
\fBSince\fP
.RS 4
1\&.1 
.RE
.PP
\fBAuthor\fP
.RS 4
Attila Kovacs 
.RE
.PP

.PP
References \fBcat_entry::dec\fP, \fBNOVAS_CATALOG_OBJECT\fP, \fBNOVAS_EARTH_RADIUS\fP, \fBNOVAS_EPHEM_OBJECT\fP, \fBNOVAS_KMS\fP, \fBNOVAS_ORBITAL_OBJECT\fP, \fBNOVAS_PLANET\fP, \fBNOVAS_PLANET_GRAV_Z_INIT\fP, \fBNOVAS_PLANETS\fP, \fBNOVAS_SOLAR_RADIUS\fP, \fBnovas_vlen()\fP, \fBnovas_z2v()\fP, \fBcat_entry::parallax\fP, \fBcat_entry::ra\fP, and \fBcat_entry::radialvelocity\fP\&.
.SS "double redshift_vrad (double vrad, double z)"
Applies an incremental redshift correction to a radial velocity\&. For example, you may use this function to correct a radial velocity calculated by \fC\fBrad_vel()\fP\fP or \fC\fBrad_vel2()\fP\fP for a Solar-system body to account for the gravitational redshift for light originating at a specific distance away from the body\&. For the Sun, you may want to undo the redshift correction applied for the photosphere using \fC\fBunredshift_vrad()\fP\fP first\&.
.PP
\fBParameters\fP
.RS 4
\fIvrad\fP [km/s] Radial velocity 
.br
\fIz\fP Redshift correction to apply 
.RE
.PP
\fBReturns\fP
.RS 4
[km/s] The redshift corrected radial velocity or NAN if the redshift value is invalid (errno will be set to EINVAL)\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBunredshift_vrad()\fP 
.PP
\fBgrav_redshift()\fP 
.PP
\fBnovas_z_add()\fP
.RE
.PP
\fBSince\fP
.RS 4
1\&.2 
.RE
.PP
\fBAuthor\fP
.RS 4
Attila Kovacs 
.RE
.PP

.PP
References \fBnovas_v2z()\fP, and \fBnovas_z2v()\fP\&.
.SS "double unredshift_vrad (double vrad, double z)"
Undoes an incremental redshift correction that was applied to radial velocity\&.
.PP
\fBParameters\fP
.RS 4
\fIvrad\fP [km/s] Radial velocity 
.br
\fIz\fP Redshift correction to apply 
.RE
.PP
\fBReturns\fP
.RS 4
[km/s] The radial velocity without the redshift correction or NAN if the redshift value is invalid\&. (errno will be set to EINVAL)
.RE
.PP
\fBSee also\fP
.RS 4
\fBredshift_vrad()\fP 
.PP
\fBgrav_redshift()\fP
.RE
.PP
\fBSince\fP
.RS 4
1\&.2 
.RE
.PP
\fBAuthor\fP
.RS 4
Attila Kovacs 
.RE
.PP

.PP
References \fBnovas_v2z()\fP, and \fBnovas_z2v()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SuperNOVAS from the source code\&.
